// source = https://www.digipres.org/formats/mime-types/ from 2023-12-13 - not very accurate, but containing many possible format examples
export const allMimeTypes = [
  '3d/vnd.adobe.dn+dcx',
  'application-x/geogebra-file',
  'application/abiword',
  'application/acad',
  'application/acrobat',
  'application/activemessage',
  'application/activity+json',
  'application/akn+xml',
  'application/andrew-inset',
  'application/applefile',
  'application/applefile; version="1"',
  'application/applefile; version="2"',
  'application/applixware',
  'application/atom+xml',
  'application/atom+xml;profile=opds-catalog',
  'application/atomcat+xml',
  'application/atomicmail',
  'application/atomsvc+xml',
  'application/auth-policy+xml',
  'application/autocad_dwg',
  'application/batch-smtp',
  'application/beep+xml',
  'application/binhex',
  'application/bizagi-modeler',
  'application/bson',
  'application/cals-1840',
  'application/cbor',
  'application/ccxml+xml',
  'application/cdf',
  'application/cdf+xml',
  'application/cdfv2',
  'application/cea-2018+xml',
  'application/cellml+xml',
  'application/cms',
  'application/cnrp+xml',
  'application/commonground',
  'application/conference-info+xml',
  'application/cpl+xml',
  'application/csta+xml',
  'application/cstadata+xml',
  'application/csv',
  'application/cu-seeme',
  'application/cwl',
  'application/cwl+json',
  'application/cwt',
  'application/cybercash',
  'application/dart',
  'application/dash+xml',
  'application/davmount+xml',
  'application/dbase',
  'application/dbase; version="iv"',
  'application/dbf',
  'application/dca-rft',
  'application/ddoc',
  'application/dec-dx',
  'application/dec-dx.',
  'application/dialog-info+xml',
  'application/dicom',
  'application/dif+xml',
  'application/dita+xml',
  'application/dita+xml;format=concept',
  'application/dita+xml;format=map',
  'application/dita+xml;format=task',
  'application/dita+xml;format=topic',
  'application/dita+xml;format=val',
  'application/dns',
  'application/docbook+xml',
  'application/dvcs',
  'application/dwf',
  'application/dwf; version="6.0"',
  'application/dwg',
  'application/dxf',
  'application/ecmascript',
  'application/edi-consent',
  'application/edi-x12',
  'application/edifact',
  'application/efi',
  'application/emma+xml',
  'application/emotionml+xml',
  'application/encase',
  'application/enex+xml',
  'application/epp+xml',
  'application/epub+zip',
  'application/eshop',
  'application/etl',
  'application/example',
  'application/exi',
  'application/f4m',
  'application/fastinfoset',
  'application/fastsoap',
  'application/fits',
  'application/font-sfnt',
  'application/font-tdpfr',
  'application/font-woff',
  'application/fractals',
  'application/freeheromesh.composite+hamarc',
  'application/freemind',
  'application/futuresplash',
  'application/ganttproject+xml',
  'application/gdiff',
  'application/geo+json',
  'application/geopackage+sqlite3',
  'application/geopackage+sqlite3; version="1.0 - 1.31"',
  'application/gml+xml',
  'application/gml+xml; version="3.2"',
  'application/gxf',
  'application/gzip',
  'application/gzip-compressed',
  'application/gzipped',
  'application/h224',
  'application/http',
  'application/hyperstudio',
  'application/ibe-key-request+xml',
  'application/ibe-pkg-reply+xml',
  'application/ibe-pp-data',
  'application/iges',
  'application/illustrator',
  'application/im-iscomposing+xml',
  'application/index',
  'application/index.cmd',
  'application/index.obj',
  'application/index.response',
  'application/index.vnd',
  'application/inf',
  'application/inkml+xml',
  'application/internet-shortcut',
  'application/ion',
  'application/iotp',
  'application/ipp',
  'application/isup',
  'application/itn',
  'application/java-archive',
  'application/java-serialized-object',
  'application/java-vm',
  'application/javascript',
  'application/jpg',
  'application/json',
  'application/json-patch+json',
  'application/json; version="1.x"',
  'application/json; version="2.x"',
  'application/json+oembed',
  'application/jsp',
  'application/jwcc',
  'application/kate',
  'application/kpml-request+xml',
  'application/kpml-response+xml',
  'application/kurzweil',
  'application/ld+json',
  'application/ld+json;profile="http://www.w3.org/ns/anno.jsonld"',
  'application/lost+xml',
  'application/lotus123',
  'application/lotus123; version="3.0"',
  'application/lotus123; version="4 - 5"',
  'application/lwp',
  'application/lwp; version="96"',
  'application/lwp; version="97 / millennium"',
  'application/mac-binhex',
  'application/mac-binhex40',
  'application/mac-compactpro',
  'application/macbinary',
  'application/macwriteii',
  'application/marc',
  'application/marcxml+xml',
  'application/mathematica',
  'application/mathml-content+xml',
  'application/mathml-presentation+xml',
  'application/mathml+xml',
  'application/matlab-mat',
  'application/mbms-associated-procedure-description+xml',
  'application/mbms-deregister+xml',
  'application/mbms-envelope+xml',
  'application/mbms-msk-response+xml',
  'application/mbms-msk+xml',
  'application/mbms-protection-description+xml',
  'application/mbms-reception-report+xml',
  'application/mbms-register-response+xml',
  'application/mbms-register+xml',
  'application/mbms-user-service-description+xml',
  'application/mbox',
  'application/media_control+xml',
  'application/mediaservercontrol+xml',
  'application/metalink+xml',
  'application/metalink4+xml',
  'application/mikey',
  'application/moss-keys',
  'application/moss-signature',
  'application/mosskey-data',
  'application/mosskey-request',
  'application/mp4',
  'application/mpeg4-generic',
  'application/mpeg4-iod',
  'application/mpeg4-iod-xmt',
  'application/ms-asf',
  'application/ms-tnef',
  'application/msexcel',
  'application/msonenote',
  'application/mspowerpoint',
  'application/msword',
  'application/msword; version="1.0"',
  'application/msword; version="1.x - 4.0"',
  'application/msword; version="2.0"',
  'application/msword; version="3.0"',
  'application/msword; version="4.0"',
  'application/msword; version="5.0 - 5.4"',
  'application/msword; version="5.0"',
  'application/msword; version="5.5"',
  'application/msword; version="6.0 - 2003"',
  'application/msword; version="6.0"',
  'application/msword; version="6.0 / 95"',
  'application/msword; version="97 - 2003"',
  'application/msword; version="generic"',
  'application/msword2',
  'application/msword5',
  'application/mxf',
  'application/mxf; version="operational pattern 1a"',
  'application/mxf; version="operational pattern 1b"',
  'application/mxf; version="operational pattern 1c"',
  'application/mxf; version="operational pattern 2a"',
  'application/mxf; version="operational pattern 2b"',
  'application/mxf; version="operational pattern 2c"',
  'application/mxf; version="operational pattern 3a"',
  'application/mxf; version="operational pattern 3b"',
  'application/mxf; version="operational pattern 3c"',
  'application/mxf; version="operational pattern op - atom"',
  'application/n-quads',
  'application/n-triples',
  'application/nasdata',
  'application/netcdf',
  'application/news-checkgroups',
  'application/news-groupinfo',
  'application/news-transmission',
  'application/node',
  'application/nss',
  'application/ocsp-request',
  'application/ocsp-response',
  'application/octet-stream',
  'application/octet-stream; version="generic"',
  'application/oda',
  'application/oebps-package+xml',
  'application/ogg',
  'application/omdoc+xml',
  'application/onenote',
  'application/opencomic+json',
  'application/opensearchdescription+xml',
  'application/ovf',
  'application/owl+xml',
  'application/oxps',
  'application/package',
  'application/parityfec',
  'application/patch-ops-error+xml',
  'application/pdf',
  'application/pdf; version="1.0"',
  'application/pdf; version="1.1"',
  'application/pdf; version="1.2"',
  'application/pdf; version="1.3"',
  'application/pdf; version="1.4"',
  'application/pdf; version="1.5"',
  'application/pdf; version="1.6"',
  'application/pdf; version="1.7"',
  'application/pdf; version="1a"',
  'application/pdf; version="1b"',
  'application/pdf; version="2.0"',
  'application/pdf; version="2a"',
  'application/pdf; version="2b"',
  'application/pdf; version="2u"',
  'application/pdf; version="3a"',
  'application/pdf; version="3b"',
  'application/pdf; version="3u"',
  'application/pgp',
  'application/pgp-encrypted',
  'application/pgp-keys',
  'application/pgp-signature',
  'application/photoshop',
  'application/pics-rules',
  'application/pidf-diff+xml',
  'application/pidf+xml',
  'application/pkcs10',
  'application/pkcs7-mime',
  'application/pkcs7-signature',
  'application/pkix-cert',
  'application/pkix-crl',
  'application/pkix-pkipath',
  'application/pkixcmp',
  'application/playerpro',
  'application/pls+xml',
  'application/poc-settings+xml',
  'application/postscript',
  'application/postscript; version="1.0 / 1.1"',
  'application/postscript; version="1.0"',
  'application/postscript; version="1.2"',
  'application/postscript; version="10.0"',
  'application/postscript; version="11.0"',
  'application/postscript; version="12.0"',
  'application/postscript; version="13.0"',
  'application/postscript; version="14.0"',
  'application/postscript; version="15.0"',
  'application/postscript; version="16.0"',
  'application/postscript; version="2.0"',
  'application/postscript; version="2.1"',
  'application/postscript; version="3.0 / 3.2"',
  'application/postscript; version="3.0"',
  'application/postscript; version="3.1"',
  'application/postscript; version="3"',
  'application/postscript; version="4.0"',
  'application/postscript; version="5.0 / 5.5"',
  'application/postscript; version="6.0"',
  'application/postscript; version="7.0"',
  'application/postscript; version="8.0"',
  'application/postscript; version="88"',
  'application/postscript; version="9.0"',
  'application/postscript; version="japan"',
  'application/pro_eng',
  'application/protobuf',
  'application/prs.alvestrand.titrax-sheet',
  'application/prs.cww',
  'application/prs.nprend',
  'application/prs.plucker',
  'application/qbooks',
  'application/qbookspro',
  'application/qif',
  'application/qsig',
  'application/rdf+json',
  'application/rdf+xml',
  'application/reginfo+xml',
  'application/relax-ng-compact-syntax',
  'application/remote-printing',
  'application/resource-lists-diff+xml',
  'application/resource-lists+xml',
  'application/riscos',
  'application/rlmi+xml',
  'application/rls-services+xml',
  'application/rsd+xml',
  'application/rss+xml',
  'application/rtf',
  'application/rtf; version="0"',
  'application/rtf; version="1.0 - 1.4"',
  'application/rtf; version="1.5 - 1.6"',
  'application/rtf; version="1.7"',
  'application/rtf; version="1.8"',
  'application/rtf; version="1.9"',
  'application/rtx',
  'application/samlassertion+xml',
  'application/samlmetadata+xml',
  'application/sbml',
  'application/sbml+xml',
  'application/scvp-cv-request',
  'application/scvp-cv-response',
  'application/scvp-vp-request',
  'application/scvp-vp-response',
  'application/sdp',
  'application/sereal',
  'application/sereal;version=1',
  'application/sereal;version=2',
  'application/sereal;version=3',
  'application/set-payment',
  'application/set-payment-initiation',
  'application/set-registration',
  'application/set-registration-initiation',
  'application/sgml',
  'application/sgml-open-catalog',
  'application/shf+xml',
  'application/sieve',
  'application/simple-filter+xml',
  'application/simple-message-summary',
  'application/simplesymbolcontainer',
  'application/sla',
  'application/slate',
  'application/sld',
  'application/sldworks',
  'application/smil',
  'application/smil+xml',
  'application/soap+fastinfoset',
  'application/soap+xml',
  'application/soundapp',
  'application/sparql-query',
  'application/sparql-results+json',
  'application/sparql-results+xml',
  'application/sparql-update',
  'application/spirits-event+xml',
  'application/spss-sav',
  'application/sql',
  'application/srgs',
  'application/srgs+xml',
  'application/ssdl+xml',
  'application/ssml+xml',
  'application/tei+xml',
  'application/tei+xml; version="p4"',
  'application/tei+xml; version="p5"',
  'application/tif',
  'application/tiff',
  'application/timestamp-query',
  'application/timestamp-reply',
  'application/toml',
  'application/toolbook',
  'application/trig',
  'application/ttml+xml',
  'application/tve-trigger',
  'application/typescript',
  'application/tzif',
  'application/tzif-leap',
  'application/ubjson',
  'application/ulpfec',
  'application/unigraphics',
  'application/varicad-dwb',
  'application/vemmi',
  'application/vividence.scriptfile',
  'application/vnd.3gpp.bsf+xml',
  'application/vnd.3gpp.pic-bw-large',
  'application/vnd.3gpp.pic-bw-small',
  'application/vnd.3gpp.pic-bw-var',
  'application/vnd.3gpp.sms',
  'application/vnd.3gpp2.bcmcsinfo+xml',
  'application/vnd.3gpp2.sms',
  'application/vnd.3gpp2.tcap',
  'application/vnd.3m.post-it-notes',
  'application/vnd.accpac.simply.aso',
  'application/vnd.accpac.simply.imp',
  'application/vnd.acucobol',
  'application/vnd.acucorp',
  'application/vnd.adobe.adept+xml',
  'application/vnd.adobe.aftereffects.project',
  'application/vnd.adobe.aftereffects.template',
  'application/vnd.adobe.air-application-installer-package+zip',
  'application/vnd.adobe.air-application-installer-package+zip; version="1.0"',
  'application/vnd.adobe.air-application-installer-package+zip; version="1.5"',
  'application/vnd.adobe.air-application-installer-package+zip; version="2.0"',
  'application/vnd.adobe.fla',
  'application/vnd.adobe.flash.movie',
  'application/vnd.adobe.folio+zip',
  'application/vnd.adobe.indesign-idml-package',
  'application/vnd.adobe.pdfxml',
  'application/vnd.adobe.real+dcxucf',
  'application/vnd.adobe.x-mars',
  'application/vnd.adobe.xdp+xml',
  'application/vnd.adobe.xfdf',
  'application/vnd.aether.imp',
  'application/vnd.airzip.filesecure.azf',
  'application/vnd.airzip.filesecure.azs',
  'application/vnd.amazon.ebook',
  'application/vnd.amazon.mobi8-ebook',
  'application/vnd.americandynamics.acc',
  'application/vnd.amiga.ami',
  'application/vnd.android.package-archive',
  'application/vnd.anser-web-certificate-issue-initiation',
  'application/vnd.anser-web-funds-transfer-initiation',
  'application/vnd.antix.game-component',
  'application/vnd.api+json',
  'application/vnd.apple.installer+xml',
  'application/vnd.apple.iwork',
  'application/vnd.apple.keynote',
  'application/vnd.apple.numbers',
  'application/vnd.apple.pages',
  'application/vnd.apple.pkpass',
  'application/vnd.arastra.swi',
  'application/vnd.audiograph',
  'application/vnd.autopackage',
  'application/vnd.avistar+xml',
  'application/vnd.bdoc-1.0',
  'application/vnd.bdoc-1.0; version="1"',
  'application/vnd.blueice.multipass',
  'application/vnd.bluetooth.ep.oob',
  'application/vnd.bmi',
  'application/vnd.businessobjects',
  'application/vnd.cab-jscript',
  'application/vnd.canon-cpdl',
  'application/vnd.canon-lips',
  'application/vnd.cendio.thinlinc.clientconf',
  'application/vnd.chemdraw+xml',
  'application/vnd.chess-pgn',
  'application/vnd.chipnuts.karaoke-mmd',
  'application/vnd.cinderella',
  'application/vnd.cip4-jdf+xml',
  'application/vnd.cirpack.isdn-ext',
  'application/vnd.citationstyles.style+xml',
  'application/vnd.claymore',
  'application/vnd.cloanto.rp9',
  'application/vnd.clonk.c4group',
  'application/vnd.coffeescript',
  'application/vnd.comicbook-rar',
  'application/vnd.comicbook+cbz',
  'application/vnd.comicbook+zip',
  'application/vnd.commerce-battelle',
  'application/vnd.commonspace',
  'application/vnd.contact.cmsg',
  'application/vnd.cosmocaller',
  'application/vnd.crick.clicker',
  'application/vnd.crick.clicker.keyboard',
  'application/vnd.crick.clicker.palette',
  'application/vnd.crick.clicker.template',
  'application/vnd.crick.clicker.wordbank',
  'application/vnd.criticaltools.wbs+xml',
  'application/vnd.ctc-posml',
  'application/vnd.ctct.ws+xml',
  'application/vnd.cups-pdf',
  'application/vnd.cups-postscript',
  'application/vnd.cups-ppd',
  'application/vnd.cups-raster',
  'application/vnd.cups-raw',
  'application/vnd.curl.car',
  'application/vnd.curl.pcurl',
  'application/vnd.cybank',
  'application/vnd.data-vision.rdz',
  'application/vnd.dbf',
  'application/vnd.debian.binary-package',
  'application/vnd.denovo.fcselayout-link',
  'application/vnd.dir-bi.plate-dl-nosuffix',
  'application/vnd.dna',
  'application/vnd.docker.container.image.v1+json',
  'application/vnd.docker.distribution.manifest.list.v2+json',
  'application/vnd.docker.distribution.manifest.v1+json',
  'application/vnd.docker.distribution.manifest.v2+json',
  'application/vnd.docker.image.rootfs.diff.tar.gzip',
  'application/vnd.docker.image.rootfs.foreign.diff.tar.gzip',
  'application/vnd.docker.plugin.v1+json',
  'application/vnd.dolby.mlp',
  'application/vnd.dolby.mobile.1',
  'application/vnd.dolby.mobile.2',
  'application/vnd.dpgraph',
  'application/vnd.dreamfactory',
  'application/vnd.dvb.esgcontainer',
  'application/vnd.dvb.ipdcdftnotifaccess',
  'application/vnd.dvb.ipdcesgaccess',
  'application/vnd.dvb.ipdcroaming',
  'application/vnd.dvb.iptv.alfec-base',
  'application/vnd.dvb.iptv.alfec-enhancement',
  'application/vnd.dvb.notif-aggregate-root+xml',
  'application/vnd.dvb.notif-container+xml',
  'application/vnd.dvb.notif-generic+xml',
  'application/vnd.dvb.notif-ia-msglist+xml',
  'application/vnd.dvb.notif-ia-registration-request+xml',
  'application/vnd.dvb.notif-ia-registration-response+xml',
  'application/vnd.dvb.notif-init+xml',
  'application/vnd.dxr',
  'application/vnd.dynageo',
  'application/vnd.ecdis-update',
  'application/vnd.ecowin.chart',
  'application/vnd.ecowin.filerequest',
  'application/vnd.ecowin.fileupdate',
  'application/vnd.ecowin.series',
  'application/vnd.ecowin.seriesrequest',
  'application/vnd.ecowin.seriesupdate',
  'application/vnd.emclient.accessrequest+xml',
  'application/vnd.enliven',
  'application/vnd.epson.esf',
  'application/vnd.epson.msf',
  'application/vnd.epson.quickanime',
  'application/vnd.epson.salt',
  'application/vnd.epson.ssf',
  'application/vnd.ericsson.quickcall',
  'application/vnd.eszigno3+xml',
  'application/vnd.etsi.aoc+xml',
  'application/vnd.etsi.asic-e+zip',
  'application/vnd.etsi.asic-e+zip; version="2.x"',
  'application/vnd.etsi.asic-s+zip',
  'application/vnd.etsi.cug+xml',
  'application/vnd.etsi.iptvcommand+xml',
  'application/vnd.etsi.iptvdiscovery+xml',
  'application/vnd.etsi.iptvprofile+xml',
  'application/vnd.etsi.iptvsad-bc+xml',
  'application/vnd.etsi.iptvsad-cod+xml',
  'application/vnd.etsi.iptvsad-npvr+xml',
  'application/vnd.etsi.iptvueprofile+xml',
  'application/vnd.etsi.mcid+xml',
  'application/vnd.etsi.sci+xml',
  'application/vnd.etsi.simservs+xml',
  'application/vnd.etsi.timestamp-token',
  'application/vnd.eudora.data',
  'application/vnd.ezpix-album',
  'application/vnd.ezpix-package',
  'application/vnd.f-secure.mobile',
  'application/vnd.fdf',
  'application/vnd.fdf; version="1.x"',
  'application/vnd.fdsn.mseed',
  'application/vnd.fdsn.seed',
  'application/vnd.ffsns',
  'application/vnd.fints',
  'application/vnd.flographit',
  'application/vnd.fluxtime.clip',
  'application/vnd.font-fontforge-sfd',
  'application/vnd.framemaker',
  'application/vnd.framemaker; version="2.0"',
  'application/vnd.framemaker; version="3.0"',
  'application/vnd.framemaker; version="4.0"',
  'application/vnd.framemaker; version="5.0"',
  'application/vnd.framemaker; version="5.5"',
  'application/vnd.framemaker; version="6.0"',
  'application/vnd.framemaker; version="7.0"',
  'application/vnd.framemaker; version="8.0"',
  'application/vnd.framemaker; version="9.0"',
  'application/vnd.frogans.fnc',
  'application/vnd.frogans.ltf',
  'application/vnd.fsc.weblaunch',
  'application/vnd.fujitsu.oasys',
  'application/vnd.fujitsu.oasys2',
  'application/vnd.fujitsu.oasys3',
  'application/vnd.fujitsu.oasysgp',
  'application/vnd.fujitsu.oasysprs',
  'application/vnd.fujixerox.art-ex',
  'application/vnd.fujixerox.art4',
  'application/vnd.fujixerox.ddd',
  'application/vnd.fujixerox.docuworks',
  'application/vnd.fujixerox.docuworks.binder',
  'application/vnd.fujixerox.hbpl',
  'application/vnd.fut-misnet',
  'application/vnd.fuzzysheet',
  'application/vnd.garmin.tcx+xml',
  'application/vnd.genomatix.tuxedo',
  'application/vnd.geo+json',
  'application/vnd.geogebra.file',
  'application/vnd.geogebra.file; version="1.0"',
  'application/vnd.geogebra.file; version="1.x"',
  'application/vnd.geogebra.file; version="2"',
  'application/vnd.geogebra.file; version="3"',
  'application/vnd.geogebra.file; version="4"',
  'application/vnd.geogebra.file; version="5"',
  'application/vnd.geogebra.tool',
  'application/vnd.geometry-explorer',
  'application/vnd.geoplan',
  'application/vnd.geospace',
  'application/vnd.gerber',
  'application/vnd.gmx',
  'application/vnd.google-earth.kml+xml',
  'application/vnd.google-earth.kmz',
  'application/vnd.google.protobuf',
  'application/vnd.grafeq',
  'application/vnd.gridmp',
  'application/vnd.groove-account',
  'application/vnd.groove-help',
  'application/vnd.groove-identity-message',
  'application/vnd.groove-injector',
  'application/vnd.groove-tool-message',
  'application/vnd.groove-tool-template',
  'application/vnd.groove-vcard',
  'application/vnd.gtkwave-gtkw',
  'application/vnd.handheld-entertainment+xml',
  'application/vnd.hbci',
  'application/vnd.hcl-bireports',
  'application/vnd.hdt',
  'application/vnd.hhe.lesson-player',
  'application/vnd.hp-hpgl',
  'application/vnd.hp-hpgl; version="2"',
  'application/vnd.hp-hpid',
  'application/vnd.hp-hps',
  'application/vnd.hp-jlyt',
  'application/vnd.hp-pcl',
  'application/vnd.hp-pclxl',
  'application/vnd.httphone',
  'application/vnd.hydrostatix.sof-data',
  'application/vnd.hzn-3d-crossword',
  'application/vnd.ibm.afplinedata',
  'application/vnd.ibm.electronic-media',
  'application/vnd.ibm.minipay',
  'application/vnd.ibm.modcap',
  'application/vnd.ibm.rights-management',
  'application/vnd.ibm.secure-container',
  'application/vnd.iccprofile',
  'application/vnd.igloader',
  'application/vnd.immervision-ivp',
  'application/vnd.immervision-ivu',
  'application/vnd.informedcontrol.rms+xml',
  'application/vnd.informix-visionary',
  'application/vnd.intercon.formnet',
  'application/vnd.intertrust.digibox',
  'application/vnd.intertrust.nncp',
  'application/vnd.intu.qbo',
  'application/vnd.intu.qfx',
  'application/vnd.iptc.g2.conceptitem+xml',
  'application/vnd.iptc.g2.knowledgeitem+xml',
  'application/vnd.iptc.g2.newsitem+xml',
  'application/vnd.iptc.g2.packageitem+xml',
  'application/vnd.ipunplugged.rcprofile',
  'application/vnd.irepository.package+xml',
  'application/vnd.is-xpr',
  'application/vnd.isac.fcs',
  'application/vnd.isac.fcs; version="1.0 - 3.1"',
  'application/vnd.jam',
  'application/vnd.japannet-directory-service',
  'application/vnd.japannet-jpnstore-wakeup',
  'application/vnd.japannet-payment-wakeup',
  'application/vnd.japannet-registration',
  'application/vnd.japannet-registration-wakeup',
  'application/vnd.japannet-setstore-wakeup',
  'application/vnd.japannet-verification',
  'application/vnd.japannet-verification-wakeup',
  'application/vnd.jcp.javame.midlet-rms',
  'application/vnd.jisp',
  'application/vnd.joost.joda-archive',
  'application/vnd.kahootz',
  'application/vnd.kde.karbon',
  'application/vnd.kde.kchart',
  'application/vnd.kde.kformula',
  'application/vnd.kde.kivio',
  'application/vnd.kde.kontour',
  'application/vnd.kde.kpresenter',
  'application/vnd.kde.kspread',
  'application/vnd.kde.kword',
  'application/vnd.kenameaapp',
  'application/vnd.kidspiration',
  'application/vnd.kinar',
  'application/vnd.koan',
  'application/vnd.kodak-descriptor',
  'application/vnd.las',
  'application/vnd.liberty-request+xml',
  'application/vnd.llamagraphics.life-balance.desktop',
  'application/vnd.llamagraphics.life-balance.exchange+xml',
  'application/vnd.lotus-1-2-3',
  'application/vnd.lotus-1-2-3; version="1.0"',
  'application/vnd.lotus-1-2-3; version="2.0"',
  'application/vnd.lotus-1-2-3; version="3.0"',
  'application/vnd.lotus-1-2-3; version="4 - 5"',
  'application/vnd.lotus-1-2-3; version="9.8 millennium"',
  'application/vnd.lotus-1-2-3; version="97"',
  'application/vnd.lotus-approach',
  'application/vnd.lotus-approach; version="97"',
  'application/vnd.lotus-freelance',
  'application/vnd.lotus-notes',
  'application/vnd.lotus-notes; version="2"',
  'application/vnd.lotus-notes; version="3"',
  'application/vnd.lotus-notes; version="4"',
  'application/vnd.lotus-organizer',
  'application/vnd.lotus-screencam',
  'application/vnd.lotus-wordpro',
  'application/vnd.lotus-wordpro; version="96"',
  'application/vnd.lotus-wordpro; version="97 / millennium"',
  'application/vnd.macports.portpkg',
  'application/vnd.makemusic.notation',
  'application/vnd.mapbox-vector-tile',
  'application/vnd.marlin.drm.actiontoken+xml',
  'application/vnd.marlin.drm.conftoken+xml',
  'application/vnd.marlin.drm.license+xml',
  'application/vnd.marlin.drm.mdcf',
  'application/vnd.maxar.archive.3tz+zip',
  'application/vnd.mcd',
  'application/vnd.medcalcdata',
  'application/vnd.mediastation.cdkey',
  'application/vnd.meridian-slingshot',
  'application/vnd.mfer',
  'application/vnd.mfmp',
  'application/vnd.micrografx.flo',
  'application/vnd.micrografx.igx',
  'application/vnd.microsoft.portable-executable',
  'application/vnd.microsoft.portable-executable; version="32 bit"',
  'application/vnd.microsoft.portable-executable; version="64 bit"',
  'application/vnd.microsoft.windows.thumbnail-cache; version="xp"',
  'application/vnd.mif',
  'application/vnd.mindjet.mindmanager',
  'application/vnd.minisoft-hp3000-save',
  'application/vnd.mitsubishi.misty-guard.trustweb',
  'application/vnd.mobius.daf',
  'application/vnd.mobius.dis',
  'application/vnd.mobius.mbk',
  'application/vnd.mobius.mqy',
  'application/vnd.mobius.msl',
  'application/vnd.mobius.plc',
  'application/vnd.mobius.txf',
  'application/vnd.mophun.application',
  'application/vnd.mophun.certificate',
  'application/vnd.motorola.flexsuite',
  'application/vnd.motorola.flexsuite.adsi',
  'application/vnd.motorola.flexsuite.fis',
  'application/vnd.motorola.flexsuite.gotap',
  'application/vnd.motorola.flexsuite.kmr',
  'application/vnd.motorola.flexsuite.ttc',
  'application/vnd.motorola.flexsuite.wem',
  'application/vnd.motorola.iprm',
  'application/vnd.mozilla.xul+xml',
  'application/vnd.ms-3mfdocument',
  'application/vnd.ms-access',
  'application/vnd.ms-artgalry',
  'application/vnd.ms-asf',
  'application/vnd.ms-cab-compressed',
  'application/vnd.ms-excel',
  'application/vnd.ms-excel; version="2.x"',
  'application/vnd.ms-excel; version="2"',
  'application/vnd.ms-excel; version="3.0"',
  'application/vnd.ms-excel; version="3"',
  'application/vnd.ms-excel; version="4.0"',
  'application/vnd.ms-excel; version="4s"',
  'application/vnd.ms-excel; version="4w"',
  'application/vnd.ms-excel; version="5 / 95"',
  'application/vnd.ms-excel; version="8"',
  'application/vnd.ms-excel; version="8x"',
  'application/vnd.ms-excel; version="97 - 2003"',
  'application/vnd.ms-excel.addin.macroenabled.12',
  'application/vnd.ms-excel.addin.macroenabled.12; version="2007"',
  'application/vnd.ms-excel.sheet.2',
  'application/vnd.ms-excel.sheet.3',
  'application/vnd.ms-excel.sheet.4',
  'application/vnd.ms-excel.sheet.binary.macroenabled.12',
  'application/vnd.ms-excel.sheet.binary.macroenabled.12; version="2007 onwards"',
  'application/vnd.ms-excel.sheet.macroenabled.12',
  'application/vnd.ms-excel.sheet.macroenabled.12; version="2007"',
  'application/vnd.ms-excel.template.macroenabled.12',
  'application/vnd.ms-excel.template.macroenabled.12; version="2007"',
  'application/vnd.ms-excel.workspace.3',
  'application/vnd.ms-excel.workspace.4',
  'application/vnd.ms-fontobject',
  'application/vnd.ms-fontobject; version="0x00010000"',
  'application/vnd.ms-fontobject; version="0x00020001"',
  'application/vnd.ms-fontobject; version="0x00020002"',
  'application/vnd.ms-htmlhelp',
  'application/vnd.ms-ims',
  'application/vnd.ms-lrm',
  'application/vnd.ms-officetheme',
  'application/vnd.ms-outlook',
  'application/vnd.ms-outlook-pst',
  'application/vnd.ms-package.3dmanufacturing-3dmodel+xml',
  'application/vnd.ms-pki.certstore',
  'application/vnd.ms-pki.seccat',
  'application/vnd.ms-pki.stl',
  'application/vnd.ms-playready.initiator+xml',
  'application/vnd.ms-powerpoint',
  'application/vnd.ms-powerpoint; version="2.x"',
  'application/vnd.ms-powerpoint; version="3.x"',
  'application/vnd.ms-powerpoint; version="4.x"',
  'application/vnd.ms-powerpoint; version="95"',
  'application/vnd.ms-powerpoint; version="97 - 2003"',
  'application/vnd.ms-powerpoint.addin.macroenabled.12',
  'application/vnd.ms-powerpoint.addin.macroenabled.12; version="2007"',
  'application/vnd.ms-powerpoint.presentation.macroenabled.12',
  'application/vnd.ms-powerpoint.presentation.macroenabled.12; version="2007 onwards"',
  'application/vnd.ms-powerpoint.slide.macroenabled.12',
  'application/vnd.ms-powerpoint.slide.macroenabled.12; version="2007"',
  'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
  'application/vnd.ms-powerpoint.slideshow.macroenabled.12; version="2007"',
  'application/vnd.ms-powerpoint.template.macroenabled.12',
  'application/vnd.ms-powerpoint.template.macroenabled.12; version="2007"',
  'application/vnd.ms-printing.printticket+xml',
  'application/vnd.ms-project',
  'application/vnd.ms-project; version="2000 - 2003"',
  'application/vnd.ms-project; version="2007"',
  'application/vnd.ms-project; version="2010"',
  'application/vnd.ms-project; version="4.0"',
  'application/vnd.ms-project; version="95"',
  'application/vnd.ms-project; version="98"',
  'application/vnd.ms-publisher',
  'application/vnd.ms-tnef',
  'application/vnd.ms-visio',
  'application/vnd.ms-visio.drawing',
  'application/vnd.ms-visio.drawing.macroenabled.12',
  'application/vnd.ms-visio.drawing.macroenabled.main+xml',
  'application/vnd.ms-visio.drawing.macroenabled.main+xml; version="2013"',
  'application/vnd.ms-visio.drawing.main+xml',
  'application/vnd.ms-visio.drawing.main+xml; version="2013"',
  'application/vnd.ms-visio.stencil',
  'application/vnd.ms-visio.stencil.macroenabled.12',
  'application/vnd.ms-visio.stencil.macroenabled.main+xml',
  'application/vnd.ms-visio.stencil.macroenabled.main+xml; version="2013"',
  'application/vnd.ms-visio.stencil.main+xml',
  'application/vnd.ms-visio.stencil.main+xml; version="2013"',
  'application/vnd.ms-visio.template',
  'application/vnd.ms-visio.template.macroenabled.12',
  'application/vnd.ms-visio.template.macroenabled.main+xml; version="2013"',
  'application/vnd.ms-visio.template.main+xml',
  'application/vnd.ms-visio.template.main+xml; version="2013"',
  'application/vnd.ms-wmdrm.lic-chlg-req',
  'application/vnd.ms-wmdrm.lic-resp',
  'application/vnd.ms-wmdrm.meter-chlg-req',
  'application/vnd.ms-wmdrm.meter-resp',
  'application/vnd.ms-word',
  'application/vnd.ms-word.document.macroenabled.12',
  'application/vnd.ms-word.document.macroenabled.12; version="2007 onwards"',
  'application/vnd.ms-word.template.macroenabled.12',
  'application/vnd.ms-word.template.macroenabled.12; version="2007 onwards"',
  'application/vnd.ms-works',
  'application/vnd.ms-wpl',
  'application/vnd.ms-xpsdocument',
  'application/vnd.msa-disk-image',
  'application/vnd.mseq',
  'application/vnd.msign',
  'application/vnd.multiad.creator',
  'application/vnd.multiad.creator.cif',
  'application/vnd.music-niff',
  'application/vnd.musician',
  'application/vnd.muvee.style',
  'application/vnd.ncd.control',
  'application/vnd.ncd.reference',
  'application/vnd.nervana',
  'application/vnd.netfpx',
  'application/vnd.neurolanguage.nlu',
  'application/vnd.nitf',
  'application/vnd.nitf; version="1.0"',
  'application/vnd.nitf; version="2.0"',
  'application/vnd.nitf; version="2.1"',
  'application/vnd.noblenet-directory',
  'application/vnd.noblenet-sealer',
  'application/vnd.noblenet-web',
  'application/vnd.nokia.catalogs',
  'application/vnd.nokia.conml+wbxml',
  'application/vnd.nokia.conml+xml',
  'application/vnd.nokia.iptv.config+xml',
  'application/vnd.nokia.isds-radio-presets',
  'application/vnd.nokia.landmark+wbxml',
  'application/vnd.nokia.landmark+xml',
  'application/vnd.nokia.landmarkcollection+xml',
  'application/vnd.nokia.n-gage.ac+xml',
  'application/vnd.nokia.n-gage.data',
  'application/vnd.nokia.n-gage.symbian.install',
  'application/vnd.nokia.ncd',
  'application/vnd.nokia.pcd+wbxml',
  'application/vnd.nokia.pcd+xml',
  'application/vnd.nokia.radio-preset',
  'application/vnd.nokia.radio-presets',
  'application/vnd.novadigm.edm',
  'application/vnd.novadigm.edx',
  'application/vnd.novadigm.ext',
  'application/vnd.oasis.opendocument.base',
  'application/vnd.oasis.opendocument.base; version="1.3"',
  'application/vnd.oasis.opendocument.chart',
  'application/vnd.oasis.opendocument.chart-template',
  'application/vnd.oasis.opendocument.database',
  'application/vnd.oasis.opendocument.formula',
  'application/vnd.oasis.opendocument.formula-template',
  'application/vnd.oasis.opendocument.graphics',
  'application/vnd.oasis.opendocument.graphics-flat-xml',
  'application/vnd.oasis.opendocument.graphics-template',
  'application/vnd.oasis.opendocument.graphics; version="1.0"',
  'application/vnd.oasis.opendocument.graphics; version="1.1"',
  'application/vnd.oasis.opendocument.graphics; version="1.2"',
  'application/vnd.oasis.opendocument.graphics; version="1.3"',
  'application/vnd.oasis.opendocument.image',
  'application/vnd.oasis.opendocument.image-template',
  'application/vnd.oasis.opendocument.presentation',
  'application/vnd.oasis.opendocument.presentation-flat-xml',
  'application/vnd.oasis.opendocument.presentation-template',
  'application/vnd.oasis.opendocument.presentation; version="1.0"',
  'application/vnd.oasis.opendocument.presentation; version="1.1"',
  'application/vnd.oasis.opendocument.presentation; version="1.2"',
  'application/vnd.oasis.opendocument.presentation; version="1.3"',
  'application/vnd.oasis.opendocument.spreadsheet',
  'application/vnd.oasis.opendocument.spreadsheet-template',
  'application/vnd.oasis.opendocument.spreadsheet; version="1.0"',
  'application/vnd.oasis.opendocument.spreadsheet; version="1.1"',
  'application/vnd.oasis.opendocument.spreadsheet; version="1.2"',
  'application/vnd.oasis.opendocument.spreadsheet; version="1.3"',
  'application/vnd.oasis.opendocument.text',
  'application/vnd.oasis.opendocument.text-master',
  'application/vnd.oasis.opendocument.text-template',
  'application/vnd.oasis.opendocument.text-web',
  'application/vnd.oasis.opendocument.text; version="1.0"',
  'application/vnd.oasis.opendocument.text; version="1.1"',
  'application/vnd.oasis.opendocument.text; version="1.2"',
  'application/vnd.oasis.opendocument.text; version="1.3"',
  'application/vnd.obn',
  'application/vnd.olpc-sugar',
  'application/vnd.oma-scws-config',
  'application/vnd.oma-scws-http-request',
  'application/vnd.oma-scws-http-response',
  'application/vnd.oma.bcast.associated-procedure-parameter+xml',
  'application/vnd.oma.bcast.drm-trigger+xml',
  'application/vnd.oma.bcast.imd+xml',
  'application/vnd.oma.bcast.ltkm',
  'application/vnd.oma.bcast.notification+xml',
  'application/vnd.oma.bcast.provisioningtrigger',
  'application/vnd.oma.bcast.sgboot',
  'application/vnd.oma.bcast.sgdd+xml',
  'application/vnd.oma.bcast.sgdu',
  'application/vnd.oma.bcast.simple-symbol-container',
  'application/vnd.oma.bcast.smartcard-trigger+xml',
  'application/vnd.oma.bcast.sprov+xml',
  'application/vnd.oma.bcast.stkm',
  'application/vnd.oma.dcd',
  'application/vnd.oma.dcdc',
  'application/vnd.oma.dd2+xml',
  'application/vnd.oma.drm.risd+xml',
  'application/vnd.oma.group-usage-list+xml',
  'application/vnd.oma.poc.detailed-progress-report+xml',
  'application/vnd.oma.poc.final-report+xml',
  'application/vnd.oma.poc.groups+xml',
  'application/vnd.oma.poc.invocation-descriptor+xml',
  'application/vnd.oma.poc.optimized-progress-report+xml',
  'application/vnd.oma.xcap-directory+xml',
  'application/vnd.omads-email+xml',
  'application/vnd.omads-file+xml',
  'application/vnd.omads-folder+xml',
  'application/vnd.omaloc-supl-init',
  'application/vnd.openofficeorg.extension',
  'application/vnd.openstreetmap.data+xml',
  'application/vnd.openxmlformats',
  'application/vnd.openxmlformats-officedocument.presentationml.document',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation; version="2007 onwards"',
  'application/vnd.openxmlformats-officedocument.presentationml.slide',
  'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
  'application/vnd.openxmlformats-officedocument.presentationml.slideshow; version="2007"',
  'application/vnd.openxmlformats-officedocument.presentationml.template',
  'application/vnd.openxmlformats-officedocument.presentationml.template; version="2007"',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.document',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; version="2007 onwards"',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.template; version="2007 onwards"',
  'application/vnd.openxmlformats-officedocument.vmldrawing',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document; version="2007 onwards"',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.template; version="2007 onwards"',
  'application/vnd.osa.netdeploy',
  'application/vnd.osgi.bundle',
  'application/vnd.osgi.dp',
  'application/vnd.otps.ct-kip+xml',
  'application/vnd.pagemaker',
  'application/vnd.pagemaker; version="4.0"',
  'application/vnd.pagemaker; version="5.0"',
  'application/vnd.pagemaker; version="6.0"',
  'application/vnd.pagemaker; version="6.5 - 7.0"',
  'application/vnd.palm',
  'application/vnd.paos.xml',
  'application/vnd.pdf',
  'application/vnd.pg.format',
  'application/vnd.pg.osasli',
  'application/vnd.piaccess.application-licence',
  'application/vnd.picsel',
  'application/vnd.poc.group-advertisement+xml',
  'application/vnd.pocketlearn',
  'application/vnd.powerbuilder6',
  'application/vnd.powerbuilder6-s',
  'application/vnd.powerbuilder7',
  'application/vnd.powerbuilder7-s',
  'application/vnd.powerbuilder75',
  'application/vnd.powerbuilder75-s',
  'application/vnd.preminet',
  'application/vnd.previewsystems.box',
  'application/vnd.proteus.magazine',
  'application/vnd.publishare-delta-tree',
  'application/vnd.pvi.ptid1',
  'application/vnd.pwg-multiplexed',
  'application/vnd.pwg-xhtml-print+xml',
  'application/vnd.qualcomm.brew-app-res',
  'application/vnd.quark.quarkxpress',
  'application/vnd.quark.quarkxpress; version="1 - 2"',
  'application/vnd.quark.quarkxpress; version="10.1"',
  'application/vnd.quark.quarkxpress; version="10"',
  'application/vnd.quark.quarkxpress; version="2015"',
  'application/vnd.quark.quarkxpress; version="2016"',
  'application/vnd.quark.quarkxpress; version="2017"',
  'application/vnd.quark.quarkxpress; version="2018"',
  'application/vnd.quark.quarkxpress; version="2019"',
  'application/vnd.quark.quarkxpress; version="2020"',
  'application/vnd.quark.quarkxpress; version="2021"',
  'application/vnd.quark.quarkxpress; version="3.0"',
  'application/vnd.quark.quarkxpress; version="3.1"',
  'application/vnd.quark.quarkxpress; version="3.2"',
  'application/vnd.quark.quarkxpress; version="3.3"',
  'application/vnd.quark.quarkxpress; version="4"',
  'application/vnd.quark.quarkxpress; version="5"',
  'application/vnd.quark.quarkxpress; version="6"',
  'application/vnd.quark.quarkxpress; version="7"',
  'application/vnd.quark.quarkxpress; version="8"',
  'application/vnd.quark.quarkxpress; version="9.1"',
  'application/vnd.quark.quarkxpress; version="9.2"',
  'application/vnd.quark.quarkxpress; version="9"',
  'application/vnd.quobject-quoxdocument',
  'application/vnd.rapid',
  'application/vnd.rar',
  'application/vnd.rar; version="2.0"',
  'application/vnd.rar; version="2.9"',
  'application/vnd.rar; version="5.0"',
  'application/vnd.recordare.musicxml',
  'application/vnd.recordare.musicxml+xml',
  'application/vnd.renlearn.rlprint',
  'application/vnd.rim.cod',
  'application/vnd.rn-realmedia',
  'application/vnd.rn-realmedia-vbr',
  'application/vnd.route66.link66+xml',
  'application/vnd.ruckus.download',
  'application/vnd.s3sms',
  'application/vnd.sbm.cid',
  'application/vnd.sbm.mid2',
  'application/vnd.scribus',
  'application/vnd.sealed.3df',
  'application/vnd.sealed.csf',
  'application/vnd.sealed.doc',
  'application/vnd.sealed.eml',
  'application/vnd.sealed.mht',
  'application/vnd.sealed.net',
  'application/vnd.sealed.ppt',
  'application/vnd.sealed.tiff',
  'application/vnd.sealed.xls',
  'application/vnd.sealedmedia.softseal.html',
  'application/vnd.sealedmedia.softseal.pdf',
  'application/vnd.seemail',
  'application/vnd.sema',
  'application/vnd.semd',
  'application/vnd.semf',
  'application/vnd.shana.informed.formdata',
  'application/vnd.shana.informed.formtemplate',
  'application/vnd.shana.informed.interchange',
  'application/vnd.shana.informed.package',
  'application/vnd.shp',
  'application/vnd.shx',
  'application/vnd.simtech-mindmapper',
  'application/vnd.sketchup.skp',
  'application/vnd.smaf',
  'application/vnd.smart.teacher',
  'application/vnd.software602.filler.form-xml-zip',
  'application/vnd.software602.filler.form+xml',
  'application/vnd.solent.sdkm+xml',
  'application/vnd.sparql-generate',
  'application/vnd.spotfire.dxp',
  'application/vnd.spotfire.sfs',
  'application/vnd.sqlite3',
  'application/vnd.sss-cod',
  'application/vnd.sss-dtf',
  'application/vnd.sss-ntf',
  'application/vnd.stardivision.calc',
  'application/vnd.stardivision.chart',
  'application/vnd.stardivision.draw',
  'application/vnd.stardivision.draw; version="5.x"',
  'application/vnd.stardivision.impress',
  'application/vnd.stardivision.impress-packed',
  'application/vnd.stardivision.mail',
  'application/vnd.stardivision.math',
  'application/vnd.stardivision.writer',
  'application/vnd.stardivision.writer-global',
  'application/vnd.stardivision.writer; version="5.x"',
  'application/vnd.street-stream',
  'application/vnd.sun.wadl+xml',
  'application/vnd.sun.xml.calc',
  'application/vnd.sun.xml.calc; version="1.0"',
  'application/vnd.sun.xml.calc.template',
  'application/vnd.sun.xml.draw',
  'application/vnd.sun.xml.draw; version="1.0"',
  'application/vnd.sun.xml.draw.template',
  'application/vnd.sun.xml.impress',
  'application/vnd.sun.xml.impress; version="1.0"',
  'application/vnd.sun.xml.impress.template',
  'application/vnd.sun.xml.math',
  'application/vnd.sun.xml.writer',
  'application/vnd.sun.xml.writer; version="1.0"',
  'application/vnd.sun.xml.writer.global',
  'application/vnd.sun.xml.writer.template',
  'application/vnd.sus-calendar',
  'application/vnd.svd',
  'application/vnd.swiftview-ics',
  'application/vnd.symbian.install',
  'application/vnd.syncml.dm.notification',
  'application/vnd.syncml.dm+wbxml',
  'application/vnd.syncml.dm+xml',
  'application/vnd.syncml.ds.notification',
  'application/vnd.syncml+xml',
  'application/vnd.tao.intent-module-archive',
  'application/vnd.tcpdump.pcap',
  'application/vnd.tmobile-livetv',
  'application/vnd.trid.tpt',
  'application/vnd.triscape.mxs',
  'application/vnd.trueapp',
  'application/vnd.truedoc',
  'application/vnd.ufdl',
  'application/vnd.uiq.theme',
  'application/vnd.umajin',
  'application/vnd.unity',
  'application/vnd.uof.presentation',
  'application/vnd.uoml+xml',
  'application/vnd.uplanet.alert',
  'application/vnd.uplanet.alert-wbxml',
  'application/vnd.uplanet.bearer-choice',
  'application/vnd.uplanet.bearer-choice-wbxml',
  'application/vnd.uplanet.cacheop',
  'application/vnd.uplanet.cacheop-wbxml',
  'application/vnd.uplanet.channel',
  'application/vnd.uplanet.channel-wbxml',
  'application/vnd.uplanet.list',
  'application/vnd.uplanet.list-wbxml',
  'application/vnd.uplanet.listcmd',
  'application/vnd.uplanet.listcmd-wbxml',
  'application/vnd.uplanet.signal',
  'application/vnd.valve.source.material',
  'application/vnd.vcx',
  'application/vnd.vd-study',
  'application/vnd.vectorworks',
  'application/vnd.vectorworks; version="10"',
  'application/vnd.vectorworks; version="11"',
  'application/vnd.vectorworks; version="12.5"',
  'application/vnd.vectorworks; version="2009"',
  'application/vnd.vectorworks; version="2010"',
  'application/vnd.vectorworks; version="2015"',
  'application/vnd.vectorworks; version="6"',
  'application/vnd.vectorworks; version="7"',
  'application/vnd.vectorworks; version="8"',
  'application/vnd.vectorworks; version="9"',
  'application/vnd.vidsoft.vidconference',
  'application/vnd.visio',
  'application/vnd.visio; version="2"',
  'application/vnd.visio; version="2000 - 2002"',
  'application/vnd.visio; version="2003 - 2010"',
  'application/vnd.visio; version="3"',
  'application/vnd.visio; version="4"',
  'application/vnd.visio; version="5.0"',
  'application/vnd.visio2013',
  'application/vnd.visionary',
  'application/vnd.vividence.scriptfile',
  'application/vnd.vsf',
  'application/vnd.wap.sic',
  'application/vnd.wap.slc',
  'application/vnd.wap.wbxml',
  'application/vnd.wap.wmlc',
  'application/vnd.wap.wmlscriptc',
  'application/vnd.webturbo',
  'application/vnd.wfa.wsc',
  'application/vnd.wmc',
  'application/vnd.wmf.bootstrap',
  'application/vnd.wolfram.cdf',
  'application/vnd.wolfram.cdf.text',
  'application/vnd.wolfram.mathematica',
  'application/vnd.wordperfect',
  'application/vnd.wordperfect; version="2.x"',
  'application/vnd.wordperfect; version="3.5 - 4.x"',
  'application/vnd.wordperfect; version="3.x"',
  'application/vnd.wordperfect; version="4.0 / 4.1 / 4.2"',
  'application/vnd.wordperfect; version="4.2"',
  'application/vnd.wordperfect; version="5.0"',
  'application/vnd.wordperfect; version="5.1"',
  'application/vnd.wordperfect; version="5.2"',
  'application/vnd.wordperfect; version="6 onwards"',
  'application/vnd.wordperfect; version="6.x"',
  'application/vnd.wqd',
  'application/vnd.wrq-hp3000-labelled',
  'application/vnd.wt.stf',
  'application/vnd.wv.csp+wbxml',
  'application/vnd.wv.csp+xml',
  'application/vnd.wv.ssp+xml',
  'application/vnd.wwise.bnk',
  'application/vnd.xara',
  'application/vnd.xfdl',
  'application/vnd.xfdl.webform',
  'application/vnd.xilinx.internal',
  'application/vnd.xmi+xml',
  'application/vnd.xmpie.cpkg',
  'application/vnd.xmpie.dpkg',
  'application/vnd.xmpie.plan',
  'application/vnd.xmpie.ppkg',
  'application/vnd.xmpie.xlim',
  'application/vnd.yamaha.hv-dic',
  'application/vnd.yamaha.hv-script',
  'application/vnd.yamaha.hv-voice',
  'application/vnd.yamaha.openscoreformat',
  'application/vnd.yamaha.openscoreformat.osfpvg+xml',
  'application/vnd.yamaha.smaf-audio',
  'application/vnd.yamaha.smaf-phrase',
  'application/vnd.yellowriver-custom-menu',
  'application/vnd.zul',
  'application/vnd.zzazz.deck+xml',
  'application/voicexml+xml',
  'application/wad',
  'application/warc',
  'application/warc-fields',
  'application/warc; version="1.0"',
  'application/warc; version="1.1"',
  'application/wasm',
  'application/watcherinfo+xml',
  'application/whoispp-query',
  'application/whoispp-response',
  'application/winhlp',
  'application/wita',
  'application/wordperfect',
  'application/wordperfect5.1',
  'application/wsdl+xml',
  'application/wspolicy+xml',
  'application/x-123',
  'application/x-123; version="1.0"',
  'application/x-123; version="2.0"',
  'application/x-123; version="9.8 millennium"',
  'application/x-123; version="97"',
  'application/x-3ds',
  'application/x-3dxmlplugin',
  'application/x-7z-compressed',
  'application/x-abiword',
  'application/x-acad',
  'application/x-ace-compressed',
  'application/x-adobe-indesign',
  'application/x-adobe-indesign-interchange',
  'application/x-amf',
  'application/x-amiga-disk-format',
  'application/x-apple-diskimage',
  'application/x-appleworks',
  'application/x-archive',
  'application/x-arj',
  'application/x-arj-compressed',
  'application/x-aspx',
  'application/x-astrotite-afa',
  'application/x-authorware-bin',
  'application/x-authorware-map',
  'application/x-authorware-seg',
  'application/x-autocad',
  'application/x-avm-export',
  'application/x-axcrypt',
  'application/x-b1',
  'application/x-b6z-compressed',
  'application/x-bcpio',
  'application/x-bdoc',
  'application/x-bentley-dgn',
  'application/x-berkeley-db',
  'application/x-berkeley-db;format=btree',
  'application/x-berkeley-db;format=btree;version=2',
  'application/x-berkeley-db;format=btree;version=3',
  'application/x-berkeley-db;format=btree;version=4',
  'application/x-berkeley-db;format=hash',
  'application/x-berkeley-db;format=hash;version=2',
  'application/x-berkeley-db;format=hash;version=3',
  'application/x-berkeley-db;format=hash;version=4',
  'application/x-berkeley-db;format=hash;version=5',
  'application/x-berkeley-db;format=log',
  'application/x-berkeley-db;format=queue',
  'application/x-bibtex',
  'application/x-bibtex-text-file',
  'application/x-bittorrent',
  'application/x-blender',
  'application/x-blorb',
  'application/x-bplist',
  'application/x-bytecode.elisp',
  'application/x-bzip',
  'application/x-bzip2',
  'application/x-c32-comboot-syslinux-exec',
  'application/x-cab-compressed',
  'application/x-captureone',
  'application/x-cbr',
  'application/x-cc3d',
  'application/x-cdf',
  'application/x-cdlink',
  'application/x-cfs-compressed',
  'application/x-chat',
  'application/x-chess-pgn',
  'application/x-chm',
  'application/x-chrome-package',
  'application/x-compress',
  'application/x-compressed',
  'application/x-compressed-iso',
  'application/x-coredump',
  'application/x-coreldraw',
  'application/x-corelpresentations',
  'application/x-cpio',
  'application/x-csh',
  'application/x-csv',
  'application/x-ctm',
  'application/x-dar',
  'application/x-dbase',
  'application/x-dbf',
  'application/x-dbm',
  'application/x-ddoc',
  'application/x-debian-package',
  'application/x-deflate',
  'application/x-dex',
  'application/x-dfont',
  'application/x-dgc-compressed',
  'application/x-dif',
  'application/x-director',
  'application/x-director; version="macintosh"',
  'application/x-director; version="pc"',
  'application/x-doom',
  'application/x-dosexec',
  'application/x-dtbncx+xml',
  'application/x-dtbook+xml',
  'application/x-dtbresource+xml',
  'application/x-dvi',
  'application/x-dwf; version="6.0"',
  'application/x-dwg',
  'application/x-dxb',
  'application/x-dzip',
  'application/x-eagle-schematic',
  'application/x-elc',
  'application/x-elf',
  'application/x-emf',
  'application/x-endnote-connect',
  'application/x-endnote-connection',
  'application/x-endnote-library',
  'application/x-endnote-refer',
  'application/x-endnote-style',
  'application/x-envoy',
  'application/x-epoc-app',
  'application/x-epoc-data',
  'application/x-epoc-opo',
  'application/x-epoc-sheet',
  'application/x-epoc-word',
  'application/x-erb',
  'application/x-erdas-hfa',
  'application/x-eva',
  'application/x-executable',
  'application/x-extension-ivf',
  'application/x-fdos-keyb',
  'application/x-fictionbook+xml',
  'application/x-filemaker',
  'application/x-filemaker; version="3"',
  'application/x-font-adobe-metric',
  'application/x-font-bdf',
  'application/x-font-dos',
  'application/x-font-framemaker',
  'application/x-font-ghostscript',
  'application/x-font-libgrx',
  'application/x-font-linux-psf',
  'application/x-font-otf',
  'application/x-font-pcf',
  'application/x-font-pf2',
  'application/x-font-printer-metric',
  'application/x-font-snf',
  'application/x-font-speedo',
  'application/x-font-sunos-news',
  'application/x-font-ttf',
  'application/x-font-type1',
  'application/x-font-vfont',
  'application/x-foxmail',
  'application/x-frame',
  'application/x-freehand',
  'application/x-freemind',
  'application/x-futuresplash',
  'application/x-gca-compressed',
  'application/x-gettext-translation',
  'application/x-glksave',
  'application/x-glulx',
  'application/x-gnucash',
  'application/x-gnumeric',
  'application/x-gnumeric-spreadsheet',
  'application/x-gramps-xml',
  'application/x-grib',
  'application/x-grisbi',
  'application/x-gtar',
  'application/x-gunzip',
  'application/x-gzip',
  'application/x-gzip-compressed',
  'application/x-hdf',
  'application/x-hdf5',
  'application/x-httpd-java',
  'application/x-httpd-jsp',
  'application/x-httpd-php',
  'application/x-hwp',
  'application/x-hwp-v5',
  'application/x-ia-arc',
  'application/x-ibooks+zip',
  'application/x-iff',
  'application/x-indesign',
  'application/x-inf',
  'application/x-internet-archive',
  'application/x-internet-archive; version="1.0"',
  'application/x-ipynb+json',
  'application/x-isatab',
  'application/x-isatab-assay',
  'application/x-isatab-investigation',
  'application/x-iso9660-image',
  'application/x-itunes-ipa',
  'application/x-itunes-ipsw',
  'application/x-jackson-smile',
  'application/x-java',
  'application/x-java-jnilib',
  'application/x-java-jnlp-file',
  'application/x-java-pack200',
  'application/x-java-vm',
  'application/x-javascript',
  'application/x-jpg',
  'application/x-js-taro',
  'application/x-js-taro; version="8"',
  'application/x-jsp',
  'application/x-kchart',
  'application/x-kdelnk',
  'application/x-kicad-schematic',
  'application/x-killustrator',
  'application/x-koan',
  'application/x-kpresenter',
  'application/x-krita',
  'application/x-kspread',
  'application/x-kword',
  'application/x-latex',
  'application/x-ldraw',
  'application/x-lha',
  'application/x-lharc',
  'application/x-lightwave',
  'application/x-logisim-circuit',
  'application/x-lotus-notes',
  'application/x-lzh-compressed',
  'application/x-lzip',
  'application/x-lzma',
  'application/x-macbinary',
  'application/x-maff',
  'application/x-matlab-data',
  'application/x-matroska',
  'application/x-mgx-designer',
  'application/x-midi',
  'application/x-mif',
  'application/x-mimearchive',
  'application/x-mobipocket-ebook',
  'application/x-mod',
  'application/x-mplayer2',
  'application/x-ms-application',
  'application/x-ms-compress-kwaj',
  'application/x-ms-compress-sz',
  'application/x-ms-compress-szdd',
  'application/x-ms-installer',
  'application/x-ms-manifest',
  'application/x-ms-msm',
  'application/x-ms-mst',
  'application/x-ms-pcp',
  'application/x-ms-pdb',
  'application/x-ms-registry',
  'application/x-ms-shortcut',
  'application/x-ms-wim',
  'application/x-ms-wmd',
  'application/x-ms-wmz',
  'application/x-ms-xbap',
  'application/x-msaccess',
  'application/x-msbinder',
  'application/x-mscardfile',
  'application/x-msclip',
  'application/x-msdos-program',
  'application/x-msdownload',
  'application/x-msdownload;format=pe',
  'application/x-msdownload;format=pe-arm7',
  'application/x-msdownload;format=pe-armle',
  'application/x-msdownload;format=pe-itanium',
  'application/x-msdownload;format=pe32',
  'application/x-msdownload;format=pe64',
  'application/x-msi',
  'application/x-msmediaview',
  'application/x-msmetafile',
  'application/x-msmoney',
  'application/x-mso',
  'application/x-mspublisher',
  'application/x-mspublisher; version="1"',
  'application/x-mspublisher; version="2.0"',
  'application/x-mspublisher; version="2000"',
  'application/x-mspublisher; version="2002"',
  'application/x-mspublisher; version="2003"',
  'application/x-mspublisher; version="2007"',
  'application/x-mspublisher; version="2010"',
  'application/x-mspublisher; version="2013"',
  'application/x-mspublisher; version="2016 - 2019"',
  'application/x-mspublisher; version="95"',
  'application/x-mspublisher; version="97"',
  'application/x-mspublisher; version="98"',
  'application/x-msschedule',
  'application/x-msterminal',
  'application/x-mswrite',
  'application/x-multi-part-ldraw',
  'application/x-musescore',
  'application/x-mysql-db',
  'application/x-mysql-misam-compressed-index',
  'application/x-mysql-misam-data',
  'application/x-mysql-misam-index',
  'application/x-mysql-table-definition',
  'application/x-navi-animation',
  'application/x-ndjson',
  'application/x-netcdf',
  'application/x-norton-msg',
  'application/x-nut',
  'application/x-nzb',
  'application/x-object',
  'application/x-ofx',
  'application/x-ofx; version="1.02"',
  'application/x-ofx; version="1.03"',
  'application/x-ofx; version="1.6"',
  'application/x-ofx; version="2.0.3"',
  'application/x-ofx; version="2.1.1"',
  'application/x-ogg',
  'application/x-ole-storage',
  'application/x-oom',
  'application/x-openvpn-profile',
  'application/x-os2-msg',
  'application/x-osu-beatmap-archive',
  'application/x-pagemaker',
  'application/x-paperport',
  'application/x-par',
  'application/x-par2',
  'application/x-par3',
  'application/x-pdf',
  'application/x-pek',
  'application/x-perl',
  'application/x-photoshop',
  'application/x-pif',
  'application/x-pkcs12',
  'application/x-pkcs7-certificates',
  'application/x-pkcs7-certreqresp',
  'application/x-plist',
  'application/x-pn-mpg',
  'application/x-pocket-word',
  'application/x-powershell',
  'application/x-project',
  'application/x-project; version="1.0"',
  'application/x-project; version="3.0"',
  'application/x-project; version="4.0"',
  'application/x-prt',
  'application/x-putty-private-key',
  'application/x-python-bytecode',
  'application/x-quattro-pro',
  'application/x-rar',
  'application/x-rar-compressed',
  'application/x-raw-disk-image',
  'application/x-redhat-package-manager',
  'application/x-reiner-rsct',
  'application/x-research-info-systems',
  'application/x-riff',
  'application/x-roxio-toast',
  'application/x-rpm',
  'application/x-rpt',
  'application/x-sas',
  'application/x-sas-access',
  'application/x-sas-audit',
  'application/x-sas-backup',
  'application/x-sas-catalog',
  'application/x-sas-data',
  'application/x-sas-data-index',
  'application/x-sas-dmdb',
  'application/x-sas-fdb',
  'application/x-sas-itemstor',
  'application/x-sas-mddb',
  'application/x-sas-program-data',
  'application/x-sas-putility',
  'application/x-sas-transport',
  'application/x-sas-utility',
  'application/x-sas-view',
  'application/x-sas-xport',
  'application/x-sbx',
  'application/x-sc',
  'application/x-sea',
  'application/x-setupscript',
  'application/x-sh',
  'application/x-shar',
  'application/x-sharedlib',
  'application/x-shockwave-flash',
  'application/x-shockwave-flash; version="1"',
  'application/x-shockwave-flash; version="10"',
  'application/x-shockwave-flash; version="11"',
  'application/x-shockwave-flash; version="12"',
  'application/x-shockwave-flash; version="13"',
  'application/x-shockwave-flash; version="14"',
  'application/x-shockwave-flash; version="15"',
  'application/x-shockwave-flash; version="16"',
  'application/x-shockwave-flash; version="17"',
  'application/x-shockwave-flash; version="18"',
  'application/x-shockwave-flash; version="19"',
  'application/x-shockwave-flash; version="2"',
  'application/x-shockwave-flash; version="20"',
  'application/x-shockwave-flash; version="21"',
  'application/x-shockwave-flash; version="22"',
  'application/x-shockwave-flash; version="23"',
  'application/x-shockwave-flash; version="24"',
  'application/x-shockwave-flash; version="25"',
  'application/x-shockwave-flash; version="26"',
  'application/x-shockwave-flash; version="27"',
  'application/x-shockwave-flash; version="28"',
  'application/x-shockwave-flash; version="29"',
  'application/x-shockwave-flash; version="3"',
  'application/x-shockwave-flash; version="30"',
  'application/x-shockwave-flash; version="4"',
  'application/x-shockwave-flash; version="5"',
  'application/x-shockwave-flash; version="6"',
  'application/x-shockwave-flash; version="7"',
  'application/x-shockwave-flash; version="8"',
  'application/x-shockwave-flash; version="9"',
  'application/x-shockwave-flash2-preview',
  'application/x-shorten',
  'application/x-shortpaymentdescriptor',
  'application/x-silverlight-app',
  'application/x-sit',
  'application/x-sitx',
  'application/x-sld',
  'application/x-snappy-framed',
  'application/x-softlink-whiteboard',
  'application/x-spectrum-tzx',
  'application/x-speex',
  'application/x-spss-por',
  'application/x-spss-sav',
  'application/x-sqlite3',
  'application/x-sqlite3; version="3"',
  'application/x-star-sdv',
  'application/x-starcalc',
  'application/x-stardraw',
  'application/x-stargallery-thm',
  'application/x-staroffice-template',
  'application/x-starwriter',
  'application/x-stuffit',
  'application/x-stuffit; version="1.5"',
  'application/x-stuffit; version="1.6 - 4.5"',
  'application/x-stuffit; version="5"',
  'application/x-stuffitx',
  'application/x-sv4cpio',
  'application/x-sv4crc',
  'application/x-sylk',
  'application/x-t3vm-image',
  'application/x-tads',
  'application/x-tar',
  'application/x-tcl',
  'application/x-tex',
  'application/x-tex-tfm',
  'application/x-texinfo',
  'application/x-tif',
  'application/x-tiff',
  'application/x-tika-iworks-protected',
  'application/x-tika-java-enterprise-archive',
  'application/x-tika-java-web-archive',
  'application/x-tika-msoffice',
  'application/x-tika-msoffice-embedded',
  'application/x-tika-msoffice-embedded;format=comp_obj',
  'application/x-tika-msoffice-embedded;format=ole10_native',
  'application/x-tika-msworks-spreadsheet',
  'application/x-tika-old-excel',
  'application/x-tika-ooxml',
  'application/x-tika-ooxml-protected',
  'application/x-tika-staroffice',
  'application/x-tika-unix-dump',
  'application/x-tika-visio-ooxml',
  'application/x-troff',
  'application/x-troff-man',
  'application/x-troff-me',
  'application/x-troff-ms',
  'application/x-troff-msvideo',
  'application/x-uc2-compressed',
  'application/x-uha-compressed',
  'application/x-unix-archive',
  'application/x-url',
  'application/x-ustar',
  'application/x-vhd',
  'application/x-virtualbox-vbox',
  'application/x-virtualbox-vdi',
  'application/x-vmdk',
  'application/x-vnd.corel.designer.document+zip',
  'application/x-vnd.corel.zcf.designer.document+zip',
  'application/x-vnd.oasis.opendocument.chart',
  'application/x-vnd.oasis.opendocument.chart-template',
  'application/x-vnd.oasis.opendocument.formula',
  'application/x-vnd.oasis.opendocument.formula-template',
  'application/x-vnd.oasis.opendocument.graphics',
  'application/x-vnd.oasis.opendocument.graphics-template',
  'application/x-vnd.oasis.opendocument.image',
  'application/x-vnd.oasis.opendocument.image-template',
  'application/x-vnd.oasis.opendocument.presentation',
  'application/x-vnd.oasis.opendocument.presentation-template',
  'application/x-vnd.oasis.opendocument.spreadsheet',
  'application/x-vnd.oasis.opendocument.spreadsheet-template',
  'application/x-vnd.oasis.opendocument.text',
  'application/x-vnd.oasis.opendocument.text-master',
  'application/x-vnd.oasis.opendocument.text-template',
  'application/x-vnd.oasis.opendocument.text-web',
  'application/x-vnd.sun.xml.writer',
  'application/x-votable+xml',
  'application/x-wacz',
  'application/x-wais-source',
  'application/x-web-app-manifest+json',
  'application/x-webarchive',
  'application/x-winamp',
  'application/x-windows-installer',
  'application/x-wine-extension-inf',
  'application/x-wine-extension-reg',
  'application/x-wordstar',
  'application/x-wtml',
  'application/x-wtt',
  'application/x-www-form-urlencoded',
  'application/x-x509-ca-cert',
  'application/x-x509-user-cert',
  'application/x-xar',
  'application/x-xfig',
  'application/x-xmind',
  'application/x-xml',
  'application/x-xpinstall',
  'application/x-xz',
  'application/x-yaml',
  'application/x-zip-compressed',
  'application/x-zoo',
  'application/x400-bp',
  'application/xaml+xml',
  'application/xcap-att+xml',
  'application/xcap-caps+xml',
  'application/xcap-el+xml',
  'application/xcap-error+xml',
  'application/xcap-ns+xml',
  'application/xcon-conference-info-diff+xml',
  'application/xcon-conference-info+xml',
  'application/xenc+xml',
  'application/xhtml-voice+xml',
  'application/xhtml+xml',
  'application/xhtml+xml; version="1.0"',
  'application/xhtml+xml; version="1.1"',
  'application/xliff+xml',
  'application/xml',
  'application/xml-dtd',
  'application/xml-external-parsed-entity',
  'application/xml; version="1.0"',
  'application/xml; version="1.1"',
  'application/xml+apml',
  'application/xmpp+xml',
  'application/xop+xml',
  'application/xproc+xml',
  'application/xquery',
  'application/xslfo+xml',
  'application/xslt+xml',
  'application/xspf+xml',
  'application/xv+xml',
  'application/yang',
  'application/zip',
  'application/zlib',
  'application/zstd',
  'audio/32kadpcm',
  'audio/3gpp',
  'audio/3gpp2',
  'audio/8svx',
  'audio/aac',
  'audio/aacp',
  'audio/ac3',
  'audio/adpcm',
  'audio/aiff',
  'audio/amr',
  'audio/amr-wb',
  'audio/amr-wb+',
  'audio/application/x-pn-realmedia',
  'audio/asc',
  'audio/asf',
  'audio/atrac-advanced-lossless',
  'audio/audible',
  'audio/avi',
  'audio/basic',
  'audio/bv16',
  'audio/bv32',
  'audio/clearmode',
  'audio/cn',
  'audio/csound',
  'audio/dat12',
  'audio/dfpwm',
  'audio/dls',
  'audio/dsr-es201108',
  'audio/dsr-es202050',
  'audio/dsr-es202211',
  'audio/dsr-es202212',
  'audio/dvi4',
  'audio/eac3',
  'audio/evrc',
  'audio/evrc-qcp',
  'audio/evrc0',
  'audio/evrc1',
  'audio/evrcb',
  'audio/evrcb0',
  'audio/evrcb1',
  'audio/evrcwb',
  'audio/evrcwb0',
  'audio/evrcwb1',
  'audio/example',
  'audio/flac',
  'audio/flac; version="1.2.1"',
  'audio/g719',
  'audio/g722',
  'audio/g7221',
  'audio/g723',
  'audio/g726-16',
  'audio/g726-24',
  'audio/g726-32',
  'audio/g726-40',
  'audio/g728',
  'audio/g729',
  'audio/g7291',
  'audio/g729d',
  'audio/g729e',
  'audio/gsm',
  'audio/gsm-efr',
  'audio/ilbc',
  'audio/imelody',
  'audio/it',
  'audio/l16',
  'audio/l20',
  'audio/l24',
  'audio/l8',
  'audio/lpc',
  'audio/m',
  'audio/matroska',
  'audio/med',
  'audio/mid',
  'audio/midi',
  'audio/mobile-xmf',
  'audio/mod',
  'audio/module-xm',
  'audio/mp3',
  'audio/mp4',
  'audio/mp4a',
  'audio/mp4a-latm',
  'audio/mpa',
  'audio/mpa-robust',
  'audio/mpeg',
  'audio/mpeg3',
  'audio/mpeg4-generic',
  'audio/mpg',
  'audio/mpga',
  'audio/musepack',
  'audio/ogg',
  'audio/ogg; codecs=speex',
  'audio/opus',
  'audio/parityfec',
  'audio/pcma',
  'audio/pcma-wb',
  'audio/pcmu',
  'audio/pcmu-wb',
  'audio/prs.sid',
  'audio/prs.sid; version="1"',
  'audio/prs.sid; version="2"',
  'audio/qcelp',
  'audio/red',
  'audio/rmf',
  'audio/rtp-enc-aescm128',
  'audio/rtp-midi',
  'audio/rtx',
  'audio/s3m',
  'audio/silk',
  'audio/smv',
  'audio/smv-qcp',
  'audio/smv0',
  'audio/sp-midi',
  'audio/speex',
  'audio/t140c',
  'audio/t38',
  'audio/telephone-event',
  'audio/tone',
  'audio/tta',
  'audio/tta; version="1"',
  'audio/tta; version="2"',
  'audio/ulpfec',
  'audio/vdvi',
  'audio/vmr-wb',
  'audio/vnd.3gpp.iufp',
  'audio/vnd.4sb',
  'audio/vnd.adobe.soundbooth',
  'audio/vnd.audible.aax',
  'audio/vnd.audiokoz',
  'audio/vnd.celp',
  'audio/vnd.cisco.nse',
  'audio/vnd.cmles.radio-events',
  'audio/vnd.cns.anp1',
  'audio/vnd.cns.inf1',
  'audio/vnd.digital-winds',
  'audio/vnd.dlna.adts',
  'audio/vnd.dolby.heaac.1',
  'audio/vnd.dolby.heaac.2',
  'audio/vnd.dolby.mlp',
  'audio/vnd.dolby.mps',
  'audio/vnd.dolby.pl2',
  'audio/vnd.dolby.pl2x',
  'audio/vnd.dolby.pl2z',
  'audio/vnd.dts',
  'audio/vnd.dts.hd',
  'audio/vnd.everad.plj',
  'audio/vnd.hns.audio',
  'audio/vnd.lucent.voice',
  'audio/vnd.ms-playready.media.pya',
  'audio/vnd.nokia.mobile-xmf',
  'audio/vnd.nortel.vbk',
  'audio/vnd.nuera.ecelp4800',
  'audio/vnd.nuera.ecelp7470',
  'audio/vnd.nuera.ecelp9600',
  'audio/vnd.octel.sbc',
  'audio/vnd.qcelp',
  'audio/vnd.rhetorex.32kadpcm',
  'audio/vnd.rn-realaudio',
  'audio/vnd.rn-realaudio; version="3"',
  'audio/vnd.sealedmedia.softseal.mpeg',
  'audio/vnd.vmx.cvsd',
  'audio/vnd.wave',
  'audio/vorbis',
  'audio/vorbis-config',
  'audio/wav',
  'audio/wave',
  'audio/webm',
  'audio/x-8svx',
  'audio/x-aac',
  'audio/x-adbcm',
  'audio/x-aiff',
  'audio/x-amr-wb',
  'audio/x-ape',
  'audio/x-caf',
  'audio/x-dec-adbcm',
  'audio/x-dec-basic',
  'audio/x-dff',
  'audio/x-dsf',
  'audio/x-flac',
  'audio/x-gsm',
  'audio/x-ircam',
  'audio/x-m4a',
  'audio/x-m4b',
  'audio/x-m4p',
  'audio/x-matroska',
  'audio/x-midi',
  'audio/x-mod',
  'audio/x-mp3',
  'audio/x-mp4a',
  'audio/x-mpeg',
  'audio/x-mpeg3',
  'audio/x-mpegaudio',
  'audio/x-mpegurl',
  'audio/x-mpg',
  'audio/x-ms-wax',
  'audio/x-ms-wma',
  'audio/x-musepack',
  'audio/x-ogg',
  'audio/x-ogg-flac',
  'audio/x-ogg-pcm',
  'audio/x-oggflac',
  'audio/x-oggpcm',
  'audio/x-pn-aiff',
  'audio/x-pn-audibleaudio',
  'audio/x-pn-realaudio',
  'audio/x-pn-realaudio-plugin',
  'audio/x-pn-wav',
  'audio/x-psid',
  'audio/x-realaudio',
  'audio/x-rmf',
  'audio/x-s3m',
  'audio/x-scpls',
  'audio/x-sid',
  'audio/x-speex',
  'audio/x-tta',
  'audio/x-twinvq',
  'audio/x-voc',
  'audio/x-wav',
  'audio/x-wav; version="0 generic"',
  'audio/x-wav; version="0 mpeg encoding"',
  'audio/x-wav; version="0 pcm encoding"',
  'audio/x-wav; version="0 waveformatextensible encoding"',
  'audio/x-wav; version="1 generic"',
  'audio/x-wav; version="1 mpeg encoding"',
  'audio/x-wav; version="1 pcm encoding"',
  'audio/x-wav; version="1 waveformatextensible encoding"',
  'audio/x-wav; version="2 generic"',
  'audio/x-wav; version="2 mpeg encoding"',
  'audio/x-wav; version="2 pcm encoding"',
  'audio/x-wav; version="2 waveformatextensible encoding"',
  'audio/x-wav; version="2.0"',
  'audio/x-wav; version="2.1"',
  'audio/x-wav; version="2.2"',
  'audio/x-wv',
  'audio/x-xm',
  'audio/xm',
  'chemical/seq-aa-fasta',
  'chemical/seq-na-fasta',
  'chemical/seq-na-fastq',
  'chemical/seq-na-genbank',
  'chemical/seq-na-sff',
  'chemical/x-alchemy',
  'chemical/x-cache',
  'chemical/x-cache-csf',
  'chemical/x-cdx',
  'chemical/x-cdxml',
  'chemical/x-chemdraw',
  'chemical/x-cif',
  'chemical/x-cmdf',
  'chemical/x-cml',
  'chemical/x-csml',
  'chemical/x-ctx',
  'chemical/x-daylight-smiles',
  'chemical/x-gaussian-checkpoint',
  'chemical/x-gaussian-cube',
  'chemical/x-gaussian-input',
  'chemical/x-genbank',
  'chemical/x-jcamp-dx',
  'chemical/x-mdl-molfile',
  'chemical/x-mdl-sdfile',
  'chemical/x-mmcif',
  'chemical/x-mol2',
  'chemical/x-pdb',
  'chemical/x-vmd',
  'chemical/x-xyz',
  'drawing/dwg',
  'drawing/x-dwf; version="6.0"',
  'font/otf',
  'font/sfnt',
  'font/ttf',
  'font/woff',
  'font/woff; version="1.0"',
  'font/woff2',
  'font/woff2; version="2.0"',
  'gzip/document',
  'image/apng',
  'image/ascii-art',
  'image/avi',
  'image/avif',
  'image/avif-sequence',
  'image/bmp',
  'image/bmp; version="1.0"',
  'image/bmp; version="2.0"',
  'image/bmp; version="3.0 nt"',
  'image/bmp; version="3.0"',
  'image/bmp; version="4.0"',
  'image/bmp; version="5.0"',
  'image/bpg',
  'image/cdw',
  'image/cgm',
  'image/cgm; version="1"',
  'image/cgm; version="3"',
  'image/cgm; version="4"',
  'image/cgm; version=1; version="1"',
  'image/cgm; version=2; version="2"',
  'image/cgm; version=3; version="3"',
  'image/cgm; version=4; version="4"',
  'image/cis-cod',
  'image/dicom-rle',
  'image/dng',
  'image/emf',
  'image/emf; version="1.0"',
  'image/emf; version="2.0"',
  'image/emf; version="3.0"',
  'image/example',
  'image/fif',
  'image/fits',
  'image/flif',
  'image/g3fax',
  'image/gif',
  'image/gif; version="87a"',
  'image/gif; version="89a"',
  'image/heic',
  'image/heic-sequence',
  'image/heif',
  'image/heif-sequence',
  'image/ief',
  'image/ivg',
  'image/jbig',
  'image/jls',
  'image/jng',
  'image/jp2',
  'image/jpeg',
  'image/jpeg; version="1.0"',
  'image/jpeg; version="1.00"',
  'image/jpeg; version="1.01"',
  'image/jpeg; version="1.02"',
  'image/jpeg; version="2.0"',
  'image/jpeg; version="2.1"',
  'image/jpeg; version="2.2"',
  'image/jpeg; version="2.21"',
  'image/jpeg; version="2.3.x"',
  'image/jpeg2000',
  'image/jpeg2000-image',
  'image/jpg',
  'image/jph',
  'image/jphc',
  'image/jpm',
  'image/jpx',
  'image/jxl',
  'image/jxr',
  'image/jxs',
  'image/jxsc',
  'image/jxsi',
  'image/jxss',
  'image/ktx',
  'image/mac',
  'image/mov',
  'image/naplps',
  'image/nia',
  'image/nie',
  'image/nii',
  'image/nitf',
  'image/ntf',
  'image/openraster',
  'image/pict',
  'image/png',
  'image/png; version="1.0"',
  'image/png; version="1.1"',
  'image/png; version="1.2"',
  'image/png+json',
  'image/prs.btif',
  'image/prs.pti',
  'image/pwg-raster',
  'image/sgi',
  'image/svg-xml',
  'image/svg+xml',
  'image/svg+xml; version="1.0"',
  'image/svg+xml; version="1.1"',
  'image/t38',
  'image/tif',
  'image/tiff',
  'image/tiff-fx',
  'image/tiff; version="1.0"',
  'image/tiff; version="1.1"',
  'image/tiff; version="1.3"',
  'image/tiff; version="1.4"',
  'image/tiff; version="1.5"',
  'image/tiff; version="1.6"',
  'image/tiff; version="2.0"',
  'image/tiff; version="2.1"',
  'image/tiff; version="2.2"',
  'image/tinyvg',
  'image/urf',
  'image/vicar',
  'image/vnd-ms.dds',
  'image/vnd-svf; version="1"',
  'image/vnd-svf; version="2"',
  'image/vnd-wap-wbmp',
  'image/vnd.adobe.photoshop',
  'image/vnd.adobe.premiere',
  'image/vnd.cns.inf2',
  'image/vnd.djvu',
  'image/vnd.dwf; version="6.0"',
  'image/vnd.dwg',
  'image/vnd.dwg; version="1.0"',
  'image/vnd.dwg; version="1.2"',
  'image/vnd.dwg; version="1.3"',
  'image/vnd.dwg; version="1.4"',
  'image/vnd.dwg; version="2.0"',
  'image/vnd.dwg; version="2.1"',
  'image/vnd.dwg; version="2.2"',
  'image/vnd.dwg; version="2.5"',
  'image/vnd.dwg; version="2.6"',
  'image/vnd.dwg; version="2000 - 2002"',
  'image/vnd.dwg; version="2004 - 2005"',
  'image/vnd.dwg; version="2007 - 2008"',
  'image/vnd.dwg; version="2010 / 2011 / 2012"',
  'image/vnd.dwg; version="2013 / 2014"',
  'image/vnd.dwg; version="2018 / 2019 / 2020 / 2021"',
  'image/vnd.dwg; version="r10"',
  'image/vnd.dwg; version="r11 / 12"',
  'image/vnd.dwg; version="r13"',
  'image/vnd.dwg; version="r14"',
  'image/vnd.dwg; version="r9"',
  'image/vnd.dxb',
  'image/vnd.dxf',
  'image/vnd.dxf; version="1.0"',
  'image/vnd.dxf; version="1.2"',
  'image/vnd.dxf; version="1.3"',
  'image/vnd.dxf; version="1.4"',
  'image/vnd.dxf; version="2.0"',
  'image/vnd.dxf; version="2.1"',
  'image/vnd.dxf; version="2.2"',
  'image/vnd.dxf; version="2.5"',
  'image/vnd.dxf; version="2.6"',
  'image/vnd.dxf; version="2000 - 2002"',
  'image/vnd.dxf; version="2004 - 2006"',
  'image/vnd.dxf; version="2004 / 2005 / 2006"',
  'image/vnd.dxf; version="2007 - 2009"',
  'image/vnd.dxf; version="2007 / 2008 / 2009"',
  'image/vnd.dxf; version="2010 - 2012"',
  'image/vnd.dxf; version="2010 / 2011 / 2012"',
  'image/vnd.dxf; version="2013 - 2017"',
  'image/vnd.dxf; version="2013 / 2014 / 2015 / 2016 / 2017"',
  'image/vnd.dxf; version="2018 - 2021"',
  'image/vnd.dxf; version="2018 / 2019 / 2020"',
  'image/vnd.dxf; version="generic"',
  'image/vnd.dxf; version="r10"',
  'image/vnd.dxf; version="r11 / 12"',
  'image/vnd.dxf; version="r13"',
  'image/vnd.dxf; version="r14"',
  'image/vnd.dxf; version="r9"',
  'image/vnd.dxf;format=ascii',
  'image/vnd.dxf;format=binary',
  'image/vnd.fastbidsheet',
  'image/vnd.fpx',
  'image/vnd.fst',
  'image/vnd.fujixerox.edmics-mmr',
  'image/vnd.fujixerox.edmics-rlc',
  'image/vnd.globalgraphics.pgb',
  'image/vnd.microsoft.icon',
  'image/vnd.mix',
  'image/vnd.mix; version="1.0"',
  'image/vnd.mix; version="1"',
  'image/vnd.mozilla.apng',
  'image/vnd.ms-modi',
  'image/vnd.ms-photo',
  'image/vnd.net-fpx',
  'image/vnd.radiance',
  'image/vnd.rn-realflash',
  'image/vnd.sealed.png',
  'image/vnd.sealedmedia.softseal.gif',
  'image/vnd.sealedmedia.softseal.jpg',
  'image/vnd.svf',
  'image/vnd.tencent.tap',
  'image/vnd.valve.source.texture',
  'image/vnd.wap.wbmp',
  'image/vnd.xiff',
  'image/vnd.xiff; version="2"',
  'image/vnd.xiff; version="3"',
  'image/vnd.zbrush.pcx',
  'image/vnd.zbrush.pcx; version="0"',
  'image/vnd.zbrush.pcx; version="2"',
  'image/vnd.zbrush.pcx; version="3"',
  'image/vnd.zbrush.pcx; version="4"',
  'image/vnd.zbrush.pcx; version="5"',
  'image/vpb',
  'image/webp',
  'image/wmf',
  'image/x-3ds',
  'image/x-award-bioslogo',
  'image/x-award-bioslogo2',
  'image/x-bmp',
  'image/x-bpg',
  'image/x-canon-cr2',
  'image/x-canon-cr3',
  'image/x-canon-crw',
  'image/x-cmu-raster',
  'image/x-cmx',
  'image/x-commodore-vbm',
  'image/x-corel-cpt',
  'image/x-dcx',
  'image/x-djvu',
  'image/x-dpx',
  'image/x-dwf; version="6.0"',
  'image/x-dwg',
  'image/x-epoc-mbm',
  'image/x-epoc-sketch',
  'image/x-eps',
  'image/x-epson-erf',
  'image/x-exr',
  'image/x-exr; version="2"',
  'image/x-freehand',
  'image/x-gopro-gpr',
  'image/x-hasselblad-3fr',
  'image/x-hvif',
  'image/x-icns',
  'image/x-icon',
  'image/x-ilbm',
  'image/x-jng',
  'image/x-jp2-codestream',
  'image/x-jp2-container',
  'image/x-jpeg2000-image',
  'image/x-kodak-dcr',
  'image/x-kodak-k25',
  'image/x-kodak-kdc',
  'image/x-lotus-pic',
  'image/x-lws',
  'image/x-miff',
  'image/x-minolta-mrw',
  'image/x-mng',
  'image/x-mrsid',
  'image/x-mrsid-image',
  'image/x-ms-bmp',
  'image/x-niff',
  'image/x-nikon-nef',
  'image/x-olympus-orf',
  'image/x-paintnet',
  'image/x-pcx',
  'image/x-pentax-pef',
  'image/x-pgf',
  'image/x-photo-cd',
  'image/x-pict',
  'image/x-pict; version="1.0"',
  'image/x-pict; version="2.0"',
  'image/x-portable-anymap',
  'image/x-portable-arbitrarymap',
  'image/x-portable-bitmap',
  'image/x-portable-floatmap',
  'image/x-portable-graymap',
  'image/x-portable-pixmap',
  'image/x-psd',
  'image/x-ptx',
  'image/x-quicktime',
  'image/x-raw',
  'image/x-raw-adobe',
  'image/x-raw-canon',
  'image/x-raw-casio',
  'image/x-raw-epson',
  'image/x-raw-fuji',
  'image/x-raw-hasselblad',
  'image/x-raw-imacon',
  'image/x-raw-kodak',
  'image/x-raw-leaf',
  'image/x-raw-logitech',
  'image/x-raw-mamiya',
  'image/x-raw-minolta',
  'image/x-raw-nikon',
  'image/x-raw-olympus',
  'image/x-raw-panasonic',
  'image/x-raw-pentax',
  'image/x-raw-phaseone',
  'image/x-raw-rawzor',
  'image/x-raw-red',
  'image/x-raw-sigma',
  'image/x-raw-sony',
  'image/x-rgb',
  'image/x-sgi-bw',
  'image/x-sld',
  'image/x-sun-raster',
  'image/x-targa',
  'image/x-tga',
  'image/x-tif',
  'image/x-tiff',
  'image/x-win-bitmap',
  'image/x-wmf',
  'image/x-wpg',
  'image/x-xbitmap',
  'image/x-xbitmap; version="x10"',
  'image/x-xbitmap; version="x11"',
  'image/x-xcf',
  'image/x-xpixmap',
  'image/x-xpixmap; version="x10"',
  'image/x-xwindowdump',
  'image/x-xwindowdump; version="x10"',
  'image/x.mrsid',
  'image/xcf',
  'image/xpm',
  'image/xwd',
  'image/zvi',
  'interface/x-winamp-skin',
  'java-internal/java-html',
  'math/mml',
  'math/tex',
  'message/cpim',
  'message/delivery-status',
  'message/disposition-notification',
  'message/example',
  'message/external-body',
  'message/feedback-report',
  'message/global',
  'message/global-delivery-status',
  'message/global-disposition-notification',
  'message/global-headers',
  'message/http',
  'message/imdn+xml',
  'message/news',
  'message/partial',
  'message/rfc822',
  'message/rfc822; version="1.0"',
  'message/s-http',
  'message/sip',
  'message/sipfrag',
  'message/tracking-status',
  'message/vnd.si.simp',
  'message/x-emlx',
  'model/3mf',
  'model/e57',
  'model/example',
  'model/flt',
  'model/gltf-binary',
  'model/gltf+json',
  'model/iges',
  'model/iges; version="5.x"',
  'model/mesh',
  'model/mtl',
  'model/obj',
  'model/prc',
  'model/step',
  'model/stl',
  'model/u3d',
  'model/vnd-dwf',
  'model/vnd.adobe.dn+dcxucf',
  'model/vnd.collada+xml',
  'model/vnd.dwf',
  'model/vnd.dwf; version="6.0"',
  'model/vnd.dwfx+xps',
  'model/vnd.flatland.3dml',
  'model/vnd.gdl',
  'model/vnd.gs-gdl',
  'model/vnd.gs.gdl',
  'model/vnd.gtw',
  'model/vnd.moml+xml',
  'model/vnd.mts',
  'model/vnd.opengex',
  'model/vnd.parasolid.transmit.binary',
  'model/vnd.parasolid.transmit.text',
  'model/vnd.usdz+zip',
  'model/vnd.valve.source.compiled-map',
  'model/vnd.vtu',
  'model/vrml',
  'model/vrml; version="1.0"',
  'model/vrml; version="2.0"',
  'model/x-pov',
  'model/x.stl-ascii',
  'model/x.stl-binary',
  'model/x3d-vrml',
  'model/x3d+binary',
  'model/x3d+fastinfoset',
  'model/x3d+vrml',
  'model/x3d+xml',
  'multipart/alternative',
  'multipart/appledouble',
  'multipart/appledouble; version="1"',
  'multipart/appledouble; version="2"',
  'multipart/byteranges',
  'multipart/digest',
  'multipart/encrypted',
  'multipart/example',
  'multipart/form-data',
  'multipart/header-set',
  'multipart/mixed',
  'multipart/parallel',
  'multipart/related',
  'multipart/report',
  'multipart/signed',
  'multipart/voice-message',
  'multipart/x-tar',
  'sound/aiff',
  'test/xml',
  'tex/xml',
  'text/apl',
  'text/asp',
  'text/aspdotnet',
  'text/cache-manifest',
  'text/calendar',
  'text/coffeescript',
  'text/comma-separated-values',
  'text/css',
  'text/csv',
  'text/csv-schema',
  'text/directory',
  'text/dns',
  'text/ecmascript',
  'text/enriched',
  'text/example',
  'text/gemini',
  'text/html',
  'text/html; version="2.0"',
  'text/html; version="3.2"',
  'text/html; version="4.0"',
  'text/html; version="4.01"',
  'text/html; version="5"',
  'text/iif',
  'text/inf',
  'text/ini',
  'text/iso19139+xml',
  'text/javascript',
  'text/json',
  'text/jsx',
  'text/ldpatch',
  'text/markdown',
  'text/mirc',
  'text/mizar',
  'text/n3',
  'text/ofc',
  'text/owl-functional',
  'text/owl-manchester',
  'text/parityfec',
  'text/pdf',
  'text/plain',
  'text/play',
  'text/praat-textgrid',
  'text/properties',
  'text/prs.fallenstein.rst',
  'text/prs.lines.tag',
  'text/red',
  'text/rfc822-headers',
  'text/richtext',
  'text/rss',
  'text/rtf',
  'text/rtf; version="1.0 - 1.4"',
  'text/rtf; version="1.5 - 1.6"',
  'text/rtf; version="1.7"',
  'text/rtf; version="1.8"',
  'text/rtf; version="1.9"',
  'text/rtp-enc-aescm128',
  'text/rtx',
  'text/sgml',
  'text/shex',
  'text/t140',
  'text/tab-separated-values',
  'text/troff',
  'text/turtle',
  'text/ulpfec',
  'text/uri-list',
  'text/url',
  'text/vbscript',
  'text/vcard',
  'text/velocity',
  'text/vnd.abc',
  'text/vnd.ascii-art',
  'text/vnd.curl',
  'text/vnd.curl.dcurl',
  'text/vnd.curl.mcurl',
  'text/vnd.curl.scurl',
  'text/vnd.dmclientscript',
  'text/vnd.esmertec.theme-descriptor',
  'text/vnd.fly',
  'text/vnd.fmi.flexstor',
  'text/vnd.graphviz',
  'text/vnd.hocr+html',
  'text/vnd.in3d.3dml',
  'text/vnd.in3d.spot',
  'text/vnd.iptc.anpa',
  'text/vnd.iptc.newsml',
  'text/vnd.iptc.nitf',
  'text/vnd.latex-z',
  'text/vnd.motorola.reflex',
  'text/vnd.ms-mediapackage',
  'text/vnd.net2phone.commcenter.command',
  'text/vnd.si.uricatalogue',
  'text/vnd.sosi',
  'text/vnd.sosi; version="4.0"',
  'text/vnd.sosi; version="4.1"',
  'text/vnd.sosi; version="4.5"',
  'text/vnd.sosi; version="8.1"',
  'text/vnd.sun.j2me.app-descriptor',
  'text/vnd.trolltech.linguist',
  'text/vnd.wap.si',
  'text/vnd.wap.sl',
  'text/vnd.wap.wml',
  'text/vnd.wap.wml; version="1.1"',
  'text/vnd.wap.wmlscript',
  'text/vtt',
  'text/x-actionscript',
  'text/x-ada',
  'text/x-ansi',
  'text/x-applescript',
  'text/x-arib-bml',
  'text/x-ascii-art',
  'text/x-asciidoc',
  'text/x-asm',
  'text/x-aspectj',
  'text/x-assembly',
  'text/x-awk',
  'text/x-basic',
  'text/x-bed',
  'text/x-bibtex',
  'text/x-brainfuck',
  'text/x-c',
  'text/x-c++hdr',
  'text/x-c++src',
  'text/x-cgi',
  'text/x-chat',
  'text/x-chdr',
  'text/x-clojure',
  'text/x-cmake',
  'text/x-cobol',
  'text/x-coffeescript',
  'text/x-coldfusion',
  'text/x-comma-separated-values',
  'text/x-common-lisp',
  'text/x-crontab',
  'text/x-cross-domain-policy',
  'text/x-crystal',
  'text/x-csharp',
  'text/x-csrc',
  'text/x-csv',
  'text/x-cython',
  'text/x-d',
  'text/x-diff',
  'text/x-django',
  'text/x-dockerfile',
  'text/x-dtd',
  'text/x-dylan',
  'text/x-ebnf',
  'text/x-ecl',
  'text/x-eiffel',
  'text/x-elm',
  'text/x-emacs-lisp',
  'text/x-erlang',
  'text/x-expect',
  'text/x-factor',
  'text/x-forth',
  'text/x-fortran',
  'text/x-fsharp',
  'text/x-gfm',
  'text/x-go',
  'text/x-groovy',
  'text/x-haml',
  'text/x-haskell',
  'text/x-haxe',
  'text/x-hcl',
  'text/x-idl',
  'text/x-ini',
  'text/x-java',
  'text/x-java-properties',
  'text/x-java-source',
  'text/x-jsp',
  'text/x-julia',
  'text/x-kotlin',
  'text/x-less',
  'text/x-lex',
  'text/x-literate-haskell',
  'text/x-livescript',
  'text/x-log',
  'text/x-lua',
  'text/x-markdown',
  'text/x-mathematica',
  'text/x-matlab',
  'text/x-ml',
  'text/x-modelica',
  'text/x-modula',
  'text/x-ms-contact',
  'text/x-ms-regedit',
  'text/x-mumps',
  'text/x-nfo',
  'text/x-nginx-conf',
  'text/x-nh',
  'text/x-nsis',
  'text/x-objcsrc',
  'text/x-objectivec',
  'text/x-ocaml',
  'text/x-octave',
  'text/x-opml',
  'text/x-opml+xml',
  'text/x-oz',
  'text/x-pascal',
  'text/x-pdf',
  'text/x-perl',
  'text/x-php',
  'text/x-phyloxml+xml',
  'text/x-plsql',
  'text/x-prolog',
  'text/x-properties',
  'text/x-protobuf',
  'text/x-pug',
  'text/x-puppet',
  'text/x-python',
  'text/x-rexx',
  'text/x-rpm-spec',
  'text/x-rsrc',
  'text/x-rst',
  'text/x-ruby',
  'text/x-rustsrc',
  'text/x-sas',
  'text/x-sass',
  'text/x-scala',
  'text/x-scheme',
  'text/x-scss',
  'text/x-sed',
  'text/x-server-parsed-html',
  'text/x-server-parsed-html3',
  'text/x-setext',
  'text/x-sfv',
  'text/x-sh',
  'text/x-slim',
  'text/x-smarty',
  'text/x-soy',
  'text/x-spreadsheet',
  'text/x-sql',
  'text/x-stex',
  'text/x-stsrc',
  'text/x-swift',
  'text/x-systemverilog',
  'text/x-tcl',
  'text/x-tex',
  'text/x-texinfo',
  'text/x-textile',
  'text/x-tika-text-based-message',
  'text/x-toml',
  'text/x-tre',
  'text/x-ttcn-asn',
  'text/x-twig',
  'text/x-url',
  'text/x-uuencode',
  'text/x-vb',
  'text/x-vbasic',
  'text/x-vbdotnet',
  'text/x-vbscript',
  'text/x-vcalendar',
  'text/x-vcard',
  'text/x-verilog',
  'text/x-vhdl',
  'text/x-vmessage',
  'text/x-web-markdown',
  'text/x-webidl',
  'text/x-yacc',
  'text/x-yaml',
  'text/xml',
  'text/xml-external-parsed-entity',
  'text/xml-filterforge-filter',
  'text/xml; version="1.0"',
  'text/xml; version="1.1"',
  'text/xml+oembed',
  'text/xsl',
  'text/yaml',
  'ti-99/4a pc99 disk image',
  'txt/plain',
  'video/3gpp',
  'video/3gpp-tt',
  'video/3gpp2',
  'video/audio',
  'video/avi',
  'video/bmpeg',
  'video/bt656',
  'video/celb',
  'video/daala',
  'video/dv',
  'video/dvd',
  'video/example',
  'video/ffv1',
  'video/flc',
  'video/fli',
  'video/gvi',
  'video/h261',
  'video/h263',
  'video/h263-1998',
  'video/h263-2000',
  'video/h264',
  'video/jpeg',
  'video/jpeg2000',
  'video/jpm',
  'video/jxsv',
  'video/matroska',
  'video/matroska-3d',
  'video/mj2',
  'video/mp1s',
  'video/mp2p',
  'video/mp2t',
  'video/mp4',
  'video/mp4v-es',
  'video/mpeg',
  'video/mpeg2',
  'video/mpeg4-generic',
  'video/mpg',
  'video/mpv',
  'video/msvideo',
  'video/nv',
  'video/ogg',
  'video/parityfec',
  'video/pointer',
  'video/quicktime',
  'video/raw',
  'video/rtp-enc-aescm128',
  'video/rtx',
  'video/smpte292m',
  'video/theora',
  'video/ufmf',
  'video/ulpfec',
  'video/vc1',
  'video/vnd-vivo',
  'video/vnd.avi',
  'video/vnd.cctv',
  'video/vnd.dlna.mpeg-tts',
  'video/vnd.fvt',
  'video/vnd.hns.video',
  'video/vnd.iptvforum.1dparityfec-1010',
  'video/vnd.iptvforum.1dparityfec-2005',
  'video/vnd.iptvforum.2dparityfec-1010',
  'video/vnd.iptvforum.2dparityfec-2005',
  'video/vnd.iptvforum.ttsavc',
  'video/vnd.iptvforum.ttsmpeg2',
  'video/vnd.motorola.video',
  'video/vnd.motorola.videop',
  'video/vnd.mpegurl',
  'video/vnd.ms-playready.media.pyv',
  'video/vnd.nokia.interleaved-multimedia',
  'video/vnd.nokia.videovoip',
  'video/vnd.objectvideo',
  'video/vnd.radgamettools.bink',
  'video/vnd.radgamettools.bink; version="2"',
  'video/vnd.radgamettools.smacker',
  'video/vnd.rn-realvideo',
  'video/vnd.sealed.mpeg1',
  'video/vnd.sealed.mpeg4',
  'video/vnd.sealed.swf',
  'video/vnd.sealedmedia.softseal.mov',
  'video/vnd.vivo',
  'video/vp8',
  'video/vp9',
  'video/webm',
  'video/x-amv',
  'video/x-daala',
  'video/x-dirac',
  'video/x-dv',
  'video/x-f4v',
  'video/x-flc',
  'video/x-fli',
  'video/x-flv',
  'video/x-flv; version="1"',
  'video/x-jng',
  'video/x-m4v',
  'video/x-matroska',
  'video/x-mng',
  'video/x-mpeg',
  'video/x-mpeg2a',
  'video/x-mpg',
  'video/x-ms-asf',
  'video/x-ms-asf-plugin',
  'video/x-ms-asx',
  'video/x-ms-wm',
  'video/x-ms-wma',
  'video/x-ms-wmv',
  'video/x-ms-wmx',
  'video/x-ms-wvx',
  'video/x-msvideo',
  'video/x-ogg-rgb',
  'video/x-ogg-uvs',
  'video/x-ogg-yuv',
  'video/x-oggrgb',
  'video/x-ogguvs',
  'video/x-oggyuv',
  'video/x-ogm',
  'video/x-plt',
  'video/x-pva',
  'video/x-quicktime',
  'video/x-sgi-movie',
  'video/x-smv',
  'video/x-theora',
  'video/x-tsv',
  'wwwserver/redirection',
  'x-application/adf',
  'x-application/astound',
  'x-conference/x-cooltalk',
  'x-epoc/x-sisx-app',
  'x-world/x-3dmf',
  'x-world/x-vrml',
  'x-world/x-xvrml',
  'xml/plain',
  'yexy/plain',
];
