openapi: 3.0.2
info:
  version: 1.0.2
  description: OpenAPI type definitions for Atlassian services
  title: '@zerobias-org/types-atlassian'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
