openapi: 3.0.2
info:
  version: 1.0.1
  description: OpenAPI type definitions for Atlassian services
  title: '@zerobias-org/types-atlassian'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
components:
  schemas:
    Connection:
      $ref: '#/components/schemas/connection'
    oauthTokenProfile:
      type: object
      description: Profile for connecting to a remote system via an OAuth token as described in section 4.1 of [the OAuth RFC](https://www.rfc-editor.org/rfc/rfc6749).
      properties:
        tokenType:
          type: string
          default: bearer
          description: The type of token this is
          example: Bearer
        accessToken:
          type: string
          description: Access token provided by the OAuth Provider
          format: password
          example: MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3
        url:
          type: string
          format: url
          description: Optional URL to use for authentication
          example: https://vendorapi.com
    baseConnectionState:
      type: object
      properties:
        expiresIn:
          type: number
          format: int64
          description: Number of seconds after which the access token becomes invalid
          example: 3600
    oauthTokenState:
      type: object
      description: State object for connections leveraging the OAuth Authorization Code flow. This is essentially the Access Token Response, described in section 5.1 of [the OAuth RFC](https://www.rfc-editor.org/rfc/rfc6749).
      allOf:
        - $ref: '#/components/schemas/baseConnectionState'
        - type: object
          properties:
            tokenType:
              type: string
              default: bearer
              description: The type of token this is
              example: Bearer
            accessToken:
              type: string
              description: Access token provided by the OAuth Provider
              format: password
              example: MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3
            refreshToken:
              type: string
              description: Optional refresh token which can be used to obtain a new access token
              format: password
              example: IwOGYzYTlmM2YxOTQ5MGE3YmNmMDFkNTVk
            scope:
              type: string
              description: The scope issued to this token
              example: read
            url:
              type: string
              format: url
              description: Optional URL to use for authentication
              example: https://vendorapi.com
    connection:
      type: object
      description: Connection profile for Atlassian Cloud platform services.
      allOf:
        - $ref: '#/components/schemas/oauthTokenProfile'
        - $ref: '#/components/schemas/oauthTokenState'
        - type: object
          x-oauth-providers:
            - atlassian.oauth
          x-ui-required:
            - uri
            - email
            - apiToken
          x-ui-hidden:
            - accessToken
            - tokenType
            - refreshToken
            - expiresIn
            - scope
            - url
          properties:
            uri:
              type: string
              format: url
              description: Atlassian organization domain
              example: https://example.atlassian.net
            email:
              type: string
              description: Email address of the Atlassian Account
              format: email
              example: example@gmail.com
            apiToken:
              type: string
              description: API token, generated from the Atlassian Account
              example: f5af9f51-07e6-4332-8f1a-c0c11c1e3728
              format: password
