openapi: 3.0.2
info:
  version: 3.1.4
  description: ""
  title: '@zerobias-org/types-amazon'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
