openapi: 3.0.2
info:
  version: 2.0.8
  description: OpenApi snippets for Microsoft core types
  title: '@zerobias-org/types-microsoft'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
