openapi: 3.0.2
info:
  version: 1.0.3
  description: OpenAPI type definitions for Microsoft services
  title: '@zerobias-org/types-microsoft'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
