openapi: 3.0.2
info:
  version: 3.0.23
  description: OpenApi snippets for Google core types
  title: '@zerobias-org/types-google'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
