openapi: 3.0.2
info:
  version: 1.0.9
  description: OpenAPI type definitions for Google services
  title: '@zerobias-org/types-google'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
