openapi: 3.0.2
info:
  version: 1.0.5
  description: OpenAPI type definitions for Google services
  title: '@zerobias-org/types-google'
paths:
  /foo:
    get:
      tags:
        - foo
      operationId: getFoo
      responses:
        '204':
          description: Foo
components:
  schemas:
    GcpAccessPolicy:
      $ref: '#/components/schemas/gcpAccessPolicy'
    GcpAccessPolicyAuditConfig:
      $ref: '#/components/schemas/gcpAccessPolicyAuditConfig'
    GcpAccessPolicyAuditLogConfig:
      $ref: '#/components/schemas/gcpAccessPolicyAuditLogConfig'
    GcpAccessPolicyAuditLogConfigType:
      $ref: '#/components/schemas/gcpAccessPolicyAuditLogConfigType'
    GcpAccessPolicyBinding:
      $ref: '#/components/schemas/gcpAccessPolicyBinding'
    GcpAccessPolicyBindingCondition:
      $ref: '#/components/schemas/gcpAccessPolicyBindingCondition'
    GcpAccessPolicyVersion:
      $ref: '#/components/schemas/gcpAccessPolicyVersion'
    GcpConnection:
      $ref: '#/components/schemas/gcpConnection'
    GoogleConnection:
      $ref: '#/components/schemas/googleConnection'
    gcpAccessPolicyVersion:
      type: integer
      description: The format of the policy.
      enum:
        - 0
        - 1
        - 3
    gcpAccessPolicyAuditLogConfigType:
      type: string
      description: The log type that this config enables.
      enum:
        - log_type_unspecified
        - admin_read
        - data_write
        - data_read
    gcpAccessPolicyAuditLogConfig:
      type: object
      description: Provides the configuration for logging a type of permissions.
      properties:
        logType:
          $ref: '#/components/schemas/gcpAccessPolicyAuditLogConfigType'
        exemptedMembers:
          type: array
          description: Specifies the identities that do not cause logging for this type of permission.
          items:
            type: string
    gcpAccessPolicyAuditConfig:
      type: object
      description: Specifies the audit configuration for a service.
      properties:
        service:
          type: string
          description: Specifies a service that will be enabled for audit logging.
          example:
            - storage.googleapis.com
            - allServices
        auditLogConfigs:
          type: array
          description: The configuration for logging of each type of permission.
          items:
            $ref: '#/components/schemas/gcpAccessPolicyAuditLogConfig'
    gcpAccessPolicyBindingCondition:
      type: object
      description: The condition that is associated with this binding.
      required:
        - expression
      properties:
        expression:
          type: string
          description: Textual representation of an expression in Common Expression Language syntax.
        title:
          type: string
          description: Title for the expression, i.e. a short string describing its purpose. This can be used e.g. in UIs which allow to enter the expression.
        description:
          type: string
          description: Description of the expression. This is a longer text which describes the expression, e.g. when hovered over it in a UI.
        location:
          type: string
          description: String indicating the location of the expression for error reporting, e.g. a file name and a position in the file.
    gcpAccessPolicyBinding:
      type: object
      description: Associates members with a role.
      properties:
        role:
          type: string
          description: Role that is assigned to members.
          example:
            - roles/viewer
            - roles/editor
            - roles/owner
        members:
          type: array
          description: Specifies the identities requesting access for a Cloud Platform resource.
          items:
            type: string
        condition:
          $ref: '#/components/schemas/gcpAccessPolicyBindingCondition'
    gcpAccessPolicy:
      type: object
      description: A GCP IAM Policy. More details [here](https://cloud.google.com/iam/docs/reference/rest/v1/Policy)
      properties:
        version:
          $ref: '#/components/schemas/gcpAccessPolicyVersion'
        auditConfigs:
          type: array
          description: Specifies cloud audit logging configuration for this policy.
          items:
            $ref: '#/components/schemas/gcpAccessPolicyAuditConfig'
        bindings:
          type: array
          description: Associates a list of members to a role.
          items:
            $ref: '#/components/schemas/gcpAccessPolicyBinding'
        etag:
          type: string
          description: Optimistic concurrency control as a way to help prevent simultaneous updates of a policy from overwriting each other.
          format: byte
    oauthTokenProfile:
      type: object
      description: Profile for connecting to a remote system via an OAuth token as described in section 4.1 of [the OAuth RFC](https://www.rfc-editor.org/rfc/rfc6749).
      properties:
        tokenType:
          type: string
          default: bearer
          description: The type of token this is
          example: Bearer
        accessToken:
          type: string
          description: Access token provided by the OAuth Provider
          format: password
          example: MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3
        url:
          type: string
          format: url
          description: Optional URL to use for authentication
          example: https://vendorapi.com
    baseConnectionState:
      type: object
      properties:
        expiresIn:
          type: number
          format: int64
          description: Number of seconds after which the access token becomes invalid
          example: 3600
    oauthTokenState:
      type: object
      description: State object for connections leveraging the OAuth Authorization Code flow. This is essentially the Access Token Response, described in section 5.1 of [the OAuth RFC](https://www.rfc-editor.org/rfc/rfc6749).
      allOf:
        - $ref: '#/components/schemas/baseConnectionState'
        - type: object
          properties:
            tokenType:
              type: string
              default: bearer
              description: The type of token this is
              example: Bearer
            accessToken:
              type: string
              description: Access token provided by the OAuth Provider
              format: password
              example: MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3
            refreshToken:
              type: string
              description: Optional refresh token which can be used to obtain a new access token
              format: password
              example: IwOGYzYTlmM2YxOTQ5MGE3YmNmMDFkNTVk
            scope:
              type: string
              description: The scope issued to this token
              example: read
            url:
              type: string
              format: url
              description: Optional URL to use for authentication
              example: https://vendorapi.com
    gcpConnection:
      type: object
      allOf:
        - $ref: '#/components/schemas/oauthTokenProfile'
        - $ref: '#/components/schemas/oauthTokenState'
        - type: object
          x-oauth-providers:
            - google.oauth
          x-ui-required:
            - clientEmail
            - privateKey
          x-ui-hidden:
            - accessToken
            - tokenType
            - refreshToken
            - expiresIn
            - scope
          description: Connection Profile used to connect to Google Cloud Platform. See https://cloud.google.com/docs/authentication/production#create_service_account. If not using the `oauth` connection flow, one must provide both `clientEmail` and `privateKey` properties.
          properties:
            url:
              description: The url of the Google Cloud Platform service. See https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-nodejs.
              type: string
              format: uri
              example: https://www.googleapis.com
            clientEmail:
              description: The email of the client account. Provide this paramater when oauth is not used.
              type: string
              format: email
              example: example@gmail.com
            privateKey:
              description: The private key of the client that is base64 encoded. Provide this paramater when oauth is not used.
              type: string
              format: password
              example: LS0tLS1CRUdJTiBS U0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT2dJQkFBSkJBS2ozNEdreEZoRDkwdmNOTFlMSW5GRVg2UHB5MXRQZjlDbnpqNHA0V0dlS0xzMVB0OFF1CktVcFJLZkZMZlJZQzlBSUtqYkpUV2l0K0NxdmpXWXp2UXdFQ0F3RUFBUUpBSUpMaXhCeTJxcEZvUzREU21vRW0KbzNxR3kwdDZ6MDlBSUp0SCs1T2VSVjFiZStONGNEWUpLZmZHekRhODh2UUVOWmlSbTBHUnE2YStIUEdRTWQyawpUUUloQUtNU3Z6SUJubmk3b3QvT1NpZTJUbUpMWTRTd1RRQWV2WHlzRTJSYkZEWWRBaUVCQ1VFYVJRbk1uYnA3CjlteERYRGY2QVUwY04vUlBCamI5cVNIRGNXWkhHelVDSUcyRXM1OXo4dWdHckRZK3B4TFFud2ZvdGFkeGQrVXkKdi9PdzVUMHE1Z0lKQWlFQXlTNFJhSTlZRzhFV3gvMncwVDY3WlVWQXc4ZU9NQjZCSVVnMFhjdSszb2tDSUJPcwovNU9pUGdvVGRTeTdiY0Y5SUdwU0U4WmdHS3pnWVFWWmVOOTdZRTAwCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
    googleConnection:
      type: object
      description: Connection profile for connecting to Google services.
      required:
        - accessToken
        - apiKey
      properties:
        accessToken:
          type: string
          description: An access token with permission to access Google API. See https://developers.google.com/identity/protocols/oauth2
          format: password
          example: MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3
        apiKey:
          type: string
          description: |-
            A simple encrypted string that identifies an application in Google Cloud without any principal
            See https://cloud.google.com/docs/authentication/api-keys.
          format: password
          example: AIzaSyDaGmWKa4JsXZ-HjGw7ISLn_3namBGewQe
